//
//  LocalizationCatalog.swift
//  TelemetryApp
//
//  Created by Alex on 15.03.26.
//

import Foundation

enum LocalizationCatalog {

    static let catalog: [AppLanguage: [LocalizationKey: String]] = [
        .english: english,
        .russian: russian,
        .spanish: spanish,
        .french: french,
        .chineseSimplified: chineseSimplified,
        .hindi: hindi
    ]

    // Baseline language
    static let english: [LocalizationKey: String] = [
        .done: "Done",
        .close: "Close",
        .cancel: "Cancel",
        .loading: "Loading…",
        .settings: "Settings",
        .language: "Language",
        .openSettings: "Open Settings",

        .driverScore: "Driver Score",
        .driverScoreOneTrip: "This Trip Score",
        .recording: "Recording",
        .ready: "Ready",
        .start: "Start",
        .stop: "Stop",
        .tripHistory: "Trip History",
        .dashcam: "Dashcam",

        .driverLabel: "Driver",
        .enterDriverId: "Change Username",
        .enterDriverIdButton: "Change Username",
        .driverIdRequired: "A username is created automatically",

        .tripArchiveTitle: "Trip History (longer than 0,3 km)",
        .tripDate: "Date",
        .score: "Score",
        .km: "km",
        .kmh: "km/h",
        .noTripsInArchive: "No trips longer than 0,3 km in archive",
        .archiveLoadError: "Failed to load archive",

        .tripDuration: "Trip Duration",
        .averageSpeed: "Average Speed",
        .notEnoughData: "Not enough data",
        .excellent: "Excellent",
        .verySmooth: "Very smooth",
        
        .driverIdSection: "Username",
        .current: "Current",
        .changeDriverId: "Change Username",

        .privacy: "Privacy",
        .privacyDescription: "In this edition, technical identifiers are hidden from the public UI. You can remove locally stored app data from this device.",
        .deleteLocalData: "Delete Local Data",
        .delete: "Delete",
        .deleteLocalDataTitle: "Delete local data?",
        .deleteLocalDataMessage: "This will remove app data stored locally on this device.",

        .backgroundLocation: "Background Location",
        .backgroundLocationFooter: "For stable GPS tracking in background, iOS requires Always permission. With When In Use, background updates may be limited by the system.",
        .gpsDeniedTitle: "GPS access denied",
        .gpsDeniedMessage: "GPS access is disabled in iOS Settings (Never or restricted). Allow location access, otherwise telemetry and trips may not be recorded.",
        .openIOSSettings: "Open iOS Settings",
        .alwaysRequiredTitle: "To run the app in background, you need to change the permission to Always",
        .alwaysRequiredMessage: "Current permission is When In Use. In background, iOS may limit updates, and trip tracking/scoring may become inaccurate.",
        .requestAlways: "Open iOS Settings and Request Always",
        .locationPermissionRequiredTitle: "Location permission required",
        .locationPermissionRequiredMessage: "Allow location access to record telemetry. Always permission will be needed for stable background operation.",
        .allowLocation: "Allow Location",
        .tripRecordingInProgress: "Trip recording in progress",
        .readyToStartTrip: "Ready to start trip",
        
        .change: "Change",
        .passwordConfirmationRequired: "Password confirmation is required for this username on this device",
        .gps: "GPS",
        .unstableOperationTitle: "Operation may be unstable",
        .alwaysPermissionHint: "For reliable trip recording in background, enable Always location permission in iOS Settings.",
        .tripTime: "Trip Time",
        .distance: "Distance",
        .server: "Server",
        .deviceShort: "Device",
        .saveFishGame: "Save the Fish Game",
        .monitoring: "Monitoring",
        .activity: "Activity",
        .state: "State",
        .tripsToday: "Trips Today",
        .dayMonitoringNote: "iOS activity detection does not distinguish a private car from public transport at this layer. Right now only automotive is detected; finer classification will be added later.",
        .viewTripHistory: "Open Trip History",
        .offlineFinishMessage: "Trip finished successfully.\nTrip reports will appear after connection to the server is restored.",
        .searchingServerMessage: "Finishing trip. Looking for Telemetry server…",
        .autoFinishSearchingMessage: "Trip was auto-finished. Finishing and retrieving report…",
        .autoFinished: "Trip auto-finished",
        .tripFinishingGettingReport: "Trip finished. Retrieving report…",
        .driverAuthUnavailable: "Driver ID verification failed: EU/RU servers temporarily unavailable",
        .enableMonitoring: "Enable monitoring",
        .disableMonitoring: "Disable monitoring",
        .driver: "Driver",
        .driverIdSetupDescription: "A username is created automatically on first launch. You can change it here if you want to use your own profile.",

        .continueButton: "Continue",
        .password: "Password",
        .create: "Create",
        .signIn: "Sign In",
        .back: "Back",
        .checking: "Checking…",
        .newDriverPasswordPrompt: "This username does not exist yet. Set a password to create it.",

        .existingDriverPasswordPrompt: "This username already exists. Enter its password to use it on this device.",

        .serverStillRequiresPassword: "The server still requires a password for this username on this device.",
        .driverIdNotCreatedOnServer: "The username was not created on the server.",
       
        
        .driverLoginMissing: "Driver login is not set",

        .report: "Report",
        .reportLoading: "Loading report…",
        .reportLoadError: "Failed to load report",
        
        .preliminaryReport: "Preliminary report",
        .batchData: "Batch data",
        .sent: "Sent",
        .notSent: "Not sent",
        .total: "Total",
        .serverProcessing: "Still processing on server",
        .autoFinishLabel: "Finish: Auto",
        .drivingMode: "Driving Mode",
        .drivingLoad: "Driving Load",
        .yourAverageRating: "Your average rating",
        .countedTripsYouHave: "Counted trips you have",
        .comparisonUnavailable: "Comparison is not available yet",
        .eventSummary: "Event Summary",
        .dangerousManeuvers: "Dangerous maneuvers",
        .skidRisk: "Skid risk",
        .roadAnomalies: "Road anomalies",
        .detailsV2: "What affected the score",
        .details: "Details",
        .poor: "Poor",
        .normal: "Normal",
        .good: "Good",
        .needsMoreCare: "Needs more care",
        .someSharpMoments: "Some sharp moments",
        .almostPerfect: "Almost perfect",
        .outOf: "out of",
        .driversGenitive: "drivers",
        .betterThanPrevTripsPrefix: "Better than",
        .betterThanPrevTripsSuffix: "of your previous trips",
        .betterThanAllTripsPrefix: "Better than",
        .betterThanAllTripsSuffix: "of all drivers' trips",
        .totalTripsCounted: "Total trips counted",
        .tripReportTitle: "Trip Report",
        
        .yourTrip: "Your Trip",
        .totals: "Totals",
        .stops: "Stops",
        .comparison: "Comparison",
        .startLabel: "Start",
        .finishLabel: "Finish",
        .meters: "m",
        .vsPreviousTrip: "Vs your previous trips",
        .vsAllTrips: "Vs all drivers trips",
        .previousTripsDriver: "Previous trips (driver)",
        .allTripsInDatabase: "All trips in database",
        .driverRank: "Driver rank",
        .totalDrivers: "Total drivers",
        .driverAverageScore: "Driver average score",
        .driverTripsCount: "Driver trips count",
        
        .drivingModeMixed: "Mixed",
        .drivingModeCity: "City",
        .drivingModeHighway: "Highway",
        .drivingModeUnknown: "Unknown",
      
        
        .stopsCount: "Number of stops",
        .stopsTotal: "Total stop time",
        .stopsP95: "Stop duration (P95)",
        .stopsPerKm: "Stops per km",
        .seconds: "sec",
        
        .eventClassesV2: "Event Classes",
        .eventClassSharpHelp: "• sharp — sharp maneuver. There is risk, but it is usually controlled.",
        .eventClassEmergencyHelp: "• emergency — emergency maneuver. More severe than the threshold, higher risk.",
        .eventClassAccelBrakeTurnHelp: "• accel/brake/turn — based on acceleration projections (a_long_g / a_lat_g).",
        .eventClassAccelBrakeInTurnHelp: "• accel_in_turn/brake_in_turn — combination of longitudinal and lateral acceleration (skid risk).",
        .eventClassRoadAnomalyHelp: "• road_anomaly — vertical spikes (a_vert_g) + severity estimation.",
        .eventClassesImportantNote: "Important: final “danger” depends on speed — scoring takes speed_m_s into account.",
        
        .glassGameRunning: "How smooth is your driving?",
        .glassGameOver: "Game over.\nYou spilled the whole glass",
        .glassGameSpilled: "Total spilled:",
        .glassGameBonus: "Refill bonus:",
        .glassGameHint: "Move the glass carefully — water reacts to motion and spills. The fish may die!",
        .glassGameSpilledShort: "Spilled:",
        .dashcamTeaserMessage:
        "Version 2.0 will surprise you here.\nDon't miss the new app release.",
        .currentSpeed: "Current speed",
        
        .accelerationSharp: "Acceleration (sharp)",
        .accelerationEmergency: "Acceleration (emergency)",
        .brakingSharp: "Braking (sharp)",
        .brakingEmergency: "Braking (emergency)",
        .turnsSharp: "Turns (sharp)",
        .turnsEmergency: "Turns (emergency)",
        .accelerationInTurn: "Acceleration in turn",
        .brakingInTurn: "Braking in turn",
        .roadAnomaliesLow: "Road anomalies (low)",
        .roadAnomaliesHigh: "Road anomalies (high)",
        
        .yourDrivingLevelToday: "Your level today:",
        .betterThanDriversPercent: "better than %d%% of drivers",
        .topDriversPercent: "Top %d%% of drivers",
        
        .currentDrivingLevel: "Current driving level:",
        .scoreDeltaLastTrips: "%@ over the last 5 trips",
        .ratingFormingTripsLeft: "Rating is being formed — %d more trips needed",
        .toNextLevelLeft: "%@ left to reach %@",
        .missingDeviceId: "Missing device ID",

        .driverLevelRisky: "Risky Driver",
        .driverLevelAverage: "Calm Driver",
        .driverLevelSafe: "Confident Driver",
        .driverLevelPro: "Professional Driver",
        
        .lastFiveTripsTitle: "Last 5 trips",
        .excellentSeriesFiveOfFive: "Excellent streak: 5 of 5",
        .goodSeriesFourOfFive: "Good streak: 4 of 5",
        .decentSeriesThreeOfFive: "Not bad streak: 3 of 5",
        .tripCanBeImproved: "There is a trip that can be improved",
        .keepGreenSeriesNextTrip: "Keep the green streak in your next trip",
        .restoreGreenSeriesNextTrip: "Try to bring back the green streak in your next trip",
        .retry: "Retry",
        
        .privacyPolicy: "Privacy Policy",
        .termsOfUse: "Terms of Use",

        .account: "Account",
        .deleteAccount: "Delete Account",
        .deleteAccountTitle: "Delete account?",
        .deleteAccountMessage: "This permanently deletes your account and associated app data that we are not required to retain.",
        .unableToDeleteAccount: "Unable to delete account",
        .accountNotFound: "Account not found",
        .errorGeneric: "Something went wrong",
        .ok: "OK",

        .changeDriverDuringTripTitle: "Change driver during active trip?",
        .changeDriverDuringTripMessage: "The current trip will be stopped and finished with the current driver ID. After that, you can sign in with a new driver ID.",

        .onboardingTitle: "Drive safer and smarter",
        .onboardingAutoDetect: "Automatically detect trips",
        .onboardingSummary: "Show trip summary and driving score",
        .onboardingEvents: "Detect braking, acceleration, and turns",
        .onboardingBackground: "Keep trip recording reliable in background",
        .onboardingPermissionText: "We request Location and Motion access only to record trips, detect driving events, and calculate your driving score.",

        .crashDetected: "Crash detected",
        .crashImpactFormat: "%.2f g impact",
        
        .driverId: "Username",
        .deviceConfirmationFailed: "Unable to confirm this device. Please use a real device.",
        .loginFailedTryAgain: "Unable to sign in. Please try again.",
        
        .driverIdNotFound: "Username not found",
        .invalidPassword: "Incorrect password",
        
        .deviceNotAuthorizedForDriver: "This device is not authorized for this username",
        .archiveNotFound: "Trip history not found",
        .archiveLoadFailedGeneric: "Unable to load trip history",
        .videoArchiveTitle: "Video Archive",
        .videoArchiveLockedMessage: "Viewing and deleting recordings is temporarily unavailable during video recording.",
        .crashRecordsSection: "Crash recordings",
        .closeButton: "Close",
        .deselectAll: "Deselect all",
        .selectAll: "Select all",
        .deleteSelectedNormalTitle: "Delete selected regular recordings?",
        .noButton: "No",
        .yesButton: "Yes",
        .recordsDeleteIrreversible: "Recordings will be deleted permanently.",
        .deleteCrashRecordsTitle: "Delete crash recordings?",
        .crashDeleteFirstConfirm: "Crash recordings are stored separately. This is the first deletion confirmation.",
        .confirmDeleteCrashRecordsTitle: "Confirm crash recording deletion",
        .crashRecordsDeleteIrreversible: "Crash recordings will be deleted permanently.",
        .archiveUnavailableDuringRecordingTitle: "Archive unavailable during recording",
        .stopVideoRecordingToOpenArchive: "Stop video recording to view or delete recordings.",
        .fileUnavailableTitle: "File unavailable",
        .unableToOpenRecordingMissingSegment: "Unable to open recording. The segment file may be missing.",
        .saveToLibraryTitle: "Save to media library?",
        .saveToLibraryConfirmFormat: "Do you want to save %d recordings with a total size of %@ MB?",
        .saveCompletedTitle: "Saving completed",
        .readyShort: "Done.",
        .totalRecordsFormat: "Total recordings: %d",
        .usedStorageFormat: "Used: %.2f GB (%d%%)",
        .recordsSavedInTwoMinuteFragments: "Recordings are saved in 2-minute fragments",
        .recordingMayContainSeveralFragments: "One recording may consist of several fragments in the archive",
        .reducesDeviceLoad: "This reduces load on the device",
        .archiveEmpty: "Archive is empty",
        .archiveEmptyDescription: "After video recording, regular and crash clips will appear here.",
        .summary: "Summary",
        .normalRecords: "Regular recordings",
        .crashRecords: "Crash recordings",
        .selected: "Selected",
        .all: "All",
        .crashFilter: "Crash",
        .normalFilter: "Regular",
        .segmentFormat: "Segment %d",
        .crashBadge: "CRASH",
        .savedBadge: "SAVED",
        .recordingFragmentFormat: "Recording #%d · Fragment %d",
        .durationLabelFormat: "Duration: %@",
        .sizeGBFormat: "Size: %.2f GB",
        .saveToMediaLibrary: "Save to media library",
        .deleteNormal: "Delete regular",
        .deleteCrash: "Delete crash",
        .archiveFooterHint: "You can select recordings and save them to the media library. Deleting crash recordings requires double confirmation.",
        .videoRecordingInProgress: "Video recording in progress",
        .videoSavingInProgress: "Saving recording",
        .hideCamera: "Hide camera",
        .showCamera: "Show camera",
        .stopVideo: "Stop video",
        .camera: "Camera",
        .roadCamera: "Road",
        .driverCamera: "Driver",

        .dmsAlertCriticalTitle: "DRIVER IS FALLING ASLEEP",
        .dmsAlertCriticalSubtitle: "PULL OVER IMMEDIATELY",
        .dmsAlertWarning: "Signs of driver fatigue",
        .dmsAlertDrowsy: "Head down",
        .dmsAlertDistracted: "Watch the road",

        .smoothness: "Smoothness",
        
        .recordingTitleFormat: "Recording #%d",
        .savedToLibraryFormat: "Saved to media library: %d",
        
        .onboardingDashcamTitle: "Dashcam for trips",
        .onboardingDashcamVideoRecording: "Record video during a trip",
        .onboardingDashcamForegroundOnly: "Keep the app open while recording",
        .onboardingDashcamNoHiddenBackground: "Video recording does not run as a hidden background mode",
        .onboardingDashcamFooter: "Dashcam mode shows recording status, timer, and controls.",

        .onboardingCrashTitle: "Crash clips",
        .onboardingCrashProtectedClip: "Save a protected clip after a strong impact",
        .onboardingCrashBeforeAfter: "Keep seconds before and after the event",
        .onboardingCrashNotAutoDeleted: "Crash recordings are not deleted automatically",
        .onboardingCrashFooter: "Crash clips help link video, location, speed, and trip telemetry.",

        .onboardingPermissionsTitle: "Permissions",
        .onboardingPermissionCamera: "Camera is used to record video",
        .onboardingPermissionMicrophone: "Microphone is used only if audio recording is enabled",
        .onboardingPermissionPhotoLibrary: "Selected recordings can be saved to Photos manually",
        .onboardingPermissionsFooter: "The app will request the required permissions before dashcam mode starts.",

        .nextButton: "Next",
        .tripConfigHelpSpeedGateAccelBrakeMsTitle: "Speed gate for accel/brake",
        .tripConfigHelpSpeedGateAccelBrakeMsBody: "Minimum speed below which acceleration and braking events are not recorded.",
        .tripConfigHelpSpeedGateAccelBrakeMsMore: "Higher → fewer low-speed events, but sharp low-speed maneuvers may be missed.",
        .tripConfigHelpSpeedGateAccelBrakeMsLess: "Lower → more low-speed events, more noise and false positives.",
        .tripConfigHelpSpeedGateTurnMsTitle: "Speed gate for turns",
        .tripConfigHelpSpeedGateTurnMsBody: "Minimum speed below which turn events are not recorded.",
        .tripConfigHelpSpeedGateTurnMsMore: "Higher → fewer low-speed turns and less noise.",
        .tripConfigHelpSpeedGateTurnMsLess: "Lower → more low-speed turns and higher false-positive risk.",
        .tripConfigHelpSpeedGateCombinedMsTitle: "Speed gate for combined events in turns",
        .tripConfigHelpSpeedGateCombinedMsBody: "Minimum speed below which combined events are not recorded.",
        .tripConfigHelpSpeedGateCombinedMsMore: "Higher → fewer combined events at low speeds.",
        .tripConfigHelpSpeedGateCombinedMsLess: "Lower → more combined events at low speeds and more noise.",
        .tripConfigHelpCooldownAccelBrakeSTitle: "Cooldown accel/brake",
        .tripConfigHelpCooldownAccelBrakeSBody: "Minimum interval between acceleration or braking events.",
        .tripConfigHelpCooldownAccelBrakeSMore: "Higher → fewer repeated events.",
        .tripConfigHelpCooldownAccelBrakeSLess: "Lower → more repeated events and higher duplicate risk.",
        .tripConfigHelpCooldownTurnSTitle: "Cooldown turn",
        .tripConfigHelpCooldownTurnSBody: "Minimum interval between turn events.",
        .tripConfigHelpCooldownTurnSMore: "Higher → fewer repeated turns.",
        .tripConfigHelpCooldownTurnSLess: "Lower → more turn events during one long maneuver.",
        .tripConfigHelpCooldownCombinedSTitle: "Cooldown combined",
        .tripConfigHelpCooldownCombinedSBody: "Minimum interval between combined events.",
        .tripConfigHelpCooldownCombinedSMore: "Higher → fewer combined events.",
        .tripConfigHelpCooldownCombinedSLess: "Lower → combined events can be recorded more often.",
        .tripConfigHelpCooldownRoadSTitle: "Cooldown road anomaly",
        .tripConfigHelpCooldownRoadSBody: "Minimum interval between road anomaly events.",
        .tripConfigHelpCooldownRoadSMore: "Higher → fewer repeated events on bumps.",
        .tripConfigHelpCooldownRoadSLess: "Lower → more events on rough road.",
        .tripConfigHelpAccelSharpGTitle: "Accel threshold sharp",
        .tripConfigHelpAccelSharpGBody: "Longitudinal acceleration threshold for sharp acceleration.",
        .tripConfigHelpAccelSharpGMore: "Higher → sharp acceleration is detected less often.",
        .tripConfigHelpAccelSharpGLess: "Lower → sharp acceleration is detected more often.",
        .tripConfigHelpAccelEmergencyGTitle: "Accel threshold emergency",
        .tripConfigHelpAccelEmergencyGBody: "Longitudinal acceleration threshold for emergency acceleration.",
        .tripConfigHelpAccelEmergencyGMore: "Higher → emergency acceleration is rare.",
        .tripConfigHelpAccelEmergencyGLess: "Lower → emergency acceleration is more frequent.",
        .tripConfigHelpBrakeSharpGTitle: "Brake threshold sharp",
        .tripConfigHelpBrakeSharpGBody: "Longitudinal deceleration threshold for sharp braking.",
        .tripConfigHelpBrakeSharpGMore: "Higher → sharp braking is detected less often.",
        .tripConfigHelpBrakeSharpGLess: "Lower → sharp braking is detected more often.",
        .tripConfigHelpBrakeEmergencyGTitle: "Brake threshold emergency",
        .tripConfigHelpBrakeEmergencyGBody: "Longitudinal deceleration threshold for emergency braking.",
        .tripConfigHelpBrakeEmergencyGMore: "Higher → emergency braking is rare.",
        .tripConfigHelpBrakeEmergencyGLess: "Lower → emergency braking is more frequent.",
        .tripConfigHelpTurnSharpLatGTitle: "Turn threshold sharp",
        .tripConfigHelpTurnSharpLatGBody: "Lateral acceleration threshold for sharp turns.",
        .tripConfigHelpTurnSharpLatGMore: "Higher → sharp turns are detected less often.",
        .tripConfigHelpTurnSharpLatGLess: "Lower → sharp turns are detected more often.",
        .tripConfigHelpTurnEmergencyLatGTitle: "Turn threshold emergency",
        .tripConfigHelpTurnEmergencyLatGBody: "Lateral acceleration threshold for emergency turns.",
        .tripConfigHelpTurnEmergencyLatGMore: "Higher → emergency turns are rare.",
        .tripConfigHelpTurnEmergencyLatGLess: "Lower → emergency turns are more frequent.",
        .tripConfigHelpCombinedLatMinGTitle: "Minimum lateral g for combined events",
        .tripConfigHelpCombinedLatMinGBody: "Combined events are recorded only above this lateral acceleration.",
        .tripConfigHelpCombinedLatMinGMore: "Higher → fewer combined events.",
        .tripConfigHelpCombinedLatMinGLess: "Lower → more combined events.",
        .tripConfigHelpAccelInTurnSharpGTitle: "Accel in turn threshold sharp",
        .tripConfigHelpAccelInTurnSharpGBody: "Longitudinal acceleration threshold for sharp acceleration in a turn.",
        .tripConfigHelpAccelInTurnSharpGMore: "Higher → fewer events.",
        .tripConfigHelpAccelInTurnSharpGLess: "Lower → more events.",
        .tripConfigHelpAccelInTurnEmergencyGTitle: "Accel in turn threshold emergency",
        .tripConfigHelpAccelInTurnEmergencyGBody: "Longitudinal acceleration threshold for emergency acceleration in a turn.",
        .tripConfigHelpAccelInTurnEmergencyGMore: "Higher → rare emergency events.",
        .tripConfigHelpAccelInTurnEmergencyGLess: "Lower → more emergency events.",
        .tripConfigHelpBrakeInTurnSharpGTitle: "Brake in turn threshold sharp",
        .tripConfigHelpBrakeInTurnSharpGBody: "Longitudinal deceleration threshold for sharp braking in a turn.",
        .tripConfigHelpBrakeInTurnSharpGMore: "Higher → fewer events.",
        .tripConfigHelpBrakeInTurnSharpGLess: "Lower → more events.",
        .tripConfigHelpBrakeInTurnEmergencyGTitle: "Brake in turn threshold emergency",
        .tripConfigHelpBrakeInTurnEmergencyGBody: "Longitudinal deceleration threshold for emergency braking in a turn.",
        .tripConfigHelpBrakeInTurnEmergencyGMore: "Higher → rare emergency events.",
        .tripConfigHelpBrakeInTurnEmergencyGLess: "Lower → more emergency events.",
        .tripConfigHelpRoadWindowSTitle: "Road anomaly analysis window",
        .tripConfigHelpRoadWindowSBody: "Window duration used to calculate vertical acceleration peaks.",
        .tripConfigHelpRoadWindowSMore: "Higher → smoother detection.",
        .tripConfigHelpRoadWindowSLess: "Lower → more sensitive detection.",
        .tripConfigHelpRoadLowP2pGTitle: "Road anomaly low p2p threshold",
        .tripConfigHelpRoadLowP2pGBody: "Vertical peak-to-peak threshold for low road anomaly.",
        .tripConfigHelpRoadLowP2pGMore: "Higher → fewer low events.",
        .tripConfigHelpRoadLowP2pGLess: "Lower → more low events.",
        .tripConfigHelpRoadHighP2pGTitle: "Road anomaly high p2p threshold",
        .tripConfigHelpRoadHighP2pGBody: "Vertical peak-to-peak threshold for high road anomaly.",
        .tripConfigHelpRoadHighP2pGMore: "Higher → fewer high events.",
        .tripConfigHelpRoadHighP2pGLess: "Lower → more high events.",
        .tripConfigHelpRoadLowAbsGTitle: "Road anomaly low max threshold",
        .tripConfigHelpRoadLowAbsGBody: "Maximum vertical acceleration threshold for low road anomaly.",
        .tripConfigHelpRoadLowAbsGMore: "Higher → fewer low events.",
        .tripConfigHelpRoadLowAbsGLess: "Lower → more low events.",
        .tripConfigHelpRoadHighAbsGTitle: "Road anomaly high max threshold",
        .tripConfigHelpRoadHighAbsGBody: "Maximum vertical acceleration threshold for high road anomaly.",
        .tripConfigHelpRoadHighAbsGMore: "Higher → fewer high events.",
        .tripConfigHelpRoadHighAbsGLess: "Lower → more high events.",
        .tripConfigHelpDoubleCountWindowSTitle: "Double counting suppression window",
        .tripConfigHelpDoubleCountWindowSBody: "Window for suppressing plain events near combined events.",
        .tripConfigHelpDoubleCountWindowSMore: "Higher → stronger suppression.",
        .tripConfigHelpDoubleCountWindowSLess: "Lower → combined and plain events are counted together more often.",
        .tripConfigHelpSpeedBreakpointsMsTitle: "Speed factor breakpoints",
        .tripConfigHelpSpeedBreakpointsMsBody: "Speed points used to interpolate the speed factor.",
        .tripConfigHelpSpeedBreakpointsMsMore: "Higher values can increase high-speed penalties.",
        .tripConfigHelpSpeedBreakpointsMsLess: "Lower values soften speed penalty growth.",
        .tripConfigHelpSpeedFactorsTitle: "Speed factors",
        .tripConfigHelpSpeedFactorsBody: "Speed factor coefficients for matching breakpoints.",
        .tripConfigHelpSpeedFactorsMore: "Higher → stronger penalties at these speeds.",
        .tripConfigHelpSpeedFactorsLess: "Lower → weaker penalties at these speeds.",
        .tripConfigHelpPenaltyAccelSharpTitle: "Penalty accel sharp",
        .tripConfigHelpPenaltyAccelSharpBody: "Base penalty for sharp acceleration.",
        .tripConfigHelpPenaltyAccelSharpMore: "Higher → stronger score reduction.",
        .tripConfigHelpPenaltyAccelSharpLess: "Lower → weaker score reduction.",
        .tripConfigHelpPenaltyAccelEmergencyTitle: "Penalty accel emergency",
        .tripConfigHelpPenaltyAccelEmergencyBody: "Base penalty for emergency acceleration.",
        .tripConfigHelpPenaltyAccelEmergencyMore: "Higher → stronger score reduction.",
        .tripConfigHelpPenaltyAccelEmergencyLess: "Lower → weaker score reduction.",
        .tripConfigHelpPenaltyBrakeSharpTitle: "Penalty brake sharp",
        .tripConfigHelpPenaltyBrakeSharpBody: "Base penalty for sharp braking.",
        .tripConfigHelpPenaltyBrakeSharpMore: "Higher → stronger score reduction.",
        .tripConfigHelpPenaltyBrakeSharpLess: "Lower → weaker score reduction.",
        .tripConfigHelpPenaltyBrakeEmergencyTitle: "Penalty brake emergency",
        .tripConfigHelpPenaltyBrakeEmergencyBody: "Base penalty for emergency braking.",
        .tripConfigHelpPenaltyBrakeEmergencyMore: "Higher → stronger score reduction.",
        .tripConfigHelpPenaltyBrakeEmergencyLess: "Lower → weaker score reduction.",
        .tripConfigHelpPenaltyTurnSharpTitle: "Penalty turn sharp",
        .tripConfigHelpPenaltyTurnSharpBody: "Base penalty for sharp turns.",
        .tripConfigHelpPenaltyTurnSharpMore: "Higher → stronger score reduction.",
        .tripConfigHelpPenaltyTurnSharpLess: "Lower → weaker score reduction.",
        .tripConfigHelpPenaltyTurnEmergencyTitle: "Penalty turn emergency",
        .tripConfigHelpPenaltyTurnEmergencyBody: "Base penalty for emergency turns.",
        .tripConfigHelpPenaltyTurnEmergencyMore: "Higher → stronger score reduction.",
        .tripConfigHelpPenaltyTurnEmergencyLess: "Lower → weaker score reduction.",
        .tripConfigHelpPenaltyAccelInTurnSharpTitle: "Penalty accel in turn sharp",
        .tripConfigHelpPenaltyAccelInTurnSharpBody: "Base penalty for sharp acceleration in a turn.",
        .tripConfigHelpPenaltyAccelInTurnSharpMore: "Higher → stronger score reduction.",
        .tripConfigHelpPenaltyAccelInTurnSharpLess: "Lower → weaker score reduction.",
        .tripConfigHelpPenaltyAccelInTurnEmergencyTitle: "Penalty accel in turn emergency",
        .tripConfigHelpPenaltyAccelInTurnEmergencyBody: "Base penalty for emergency acceleration in a turn.",
        .tripConfigHelpPenaltyAccelInTurnEmergencyMore: "Higher → stronger score reduction.",
        .tripConfigHelpPenaltyAccelInTurnEmergencyLess: "Lower → weaker score reduction.",
        .tripConfigHelpPenaltyBrakeInTurnSharpTitle: "Penalty brake in turn sharp",
        .tripConfigHelpPenaltyBrakeInTurnSharpBody: "Base penalty for sharp braking in a turn.",
        .tripConfigHelpPenaltyBrakeInTurnSharpMore: "Higher → stronger score reduction.",
        .tripConfigHelpPenaltyBrakeInTurnSharpLess: "Lower → weaker score reduction.",
        .tripConfigHelpPenaltyBrakeInTurnEmergencyTitle: "Penalty brake in turn emergency",
        .tripConfigHelpPenaltyBrakeInTurnEmergencyBody: "Base penalty for emergency braking in a turn.",
        .tripConfigHelpPenaltyBrakeInTurnEmergencyMore: "Higher → stronger score reduction.",
        .tripConfigHelpPenaltyBrakeInTurnEmergencyLess: "Lower → weaker score reduction.",
        .tripConfigHelpPenaltyRoadLowTitle: "Penalty road anomaly low",
        .tripConfigHelpPenaltyRoadLowBody: "Base penalty for low road anomaly.",
        .tripConfigHelpPenaltyRoadLowMore: "Higher → stronger score reduction.",
        .tripConfigHelpPenaltyRoadLowLess: "Lower → weaker score reduction.",
        .tripConfigHelpPenaltyRoadHighTitle: "Penalty road anomaly high",
        .tripConfigHelpPenaltyRoadHighBody: "Base penalty for high road anomaly.",
        .tripConfigHelpPenaltyRoadHighMore: "Higher → stronger score reduction.",
        .tripConfigHelpPenaltyRoadHighLess: "Lower → weaker score reduction.",
        .crashTitleWithDateFormat: "CRASH %@",

        .dmsVoiceEyesClosed: "Eyes closed. Pull over safely.",
        .dmsVoiceHeadDown: "Head down. Watch the road.",
        .dmsVoiceDistractedLeft: "Driver is looking left. Watch the road.",
        .dmsVoiceDistractedRight: "Driver is looking right. Watch the road.",
        .dmsVoiceYawning: "Driver is yawning. Take a break soon.",
        .dmsVoiceFaceLost: "Face not visible. Watch the road.",
        .dmsVoiceEmergencyStop: "Pull over immediately.",
                  
            
      
    ]

    static let russian: [LocalizationKey: String] = [
        .done: "Готово",
        .close: "Закрыть",
        .cancel: "Отмена",
        .loading: "Загрузка…",
        .settings: "Настройки",
        .language: "Язык",
        .openSettings: "Открыть настройки",

        .driverScore: "Оценка вождения",
        .driverScoreOneTrip: "Рейтинг этой поездки",
        .recording: "Запись",
        .ready: "Готово",
        .start: "Старт",
        .stop: "Стоп",
        .tripHistory: "Архив поездок",
        .dashcam: "Видеорежим",

        .driverLabel: "Водитель",


        .tripArchiveTitle: "Архив поездок длиной более 0,3 км.",
        .tripDate: "Дата",
        .score: "Оценка",
        .km: "км",
        .kmh: "км/ч",
        .noTripsInArchive: "Нет поездок в архиве длиной более 0,3 км.",
        .archiveLoadError: "Ошибка загрузки архива",

        .tripDuration: "Длительность поездки",
        .averageSpeed: "Средняя скорость",
        .notEnoughData: "Недостаточно данных",
        .excellent: "Отлично",
        .verySmooth: "Очень аккуратно",
                
        .current: "Текущий",
       
        .privacy: "Конфиденциальность",
        .privacyDescription: "В данной версии приложения технические идентификаторы скрыты из публичного интерфейса. Вы можете удалить локально сохранённые данные приложения на этом устройстве.",
        .deleteLocalData: "Удалить локальные данные",
        .delete: "Удалить",
        .deleteLocalDataTitle: "Удалить локальные данные?",
        .deleteLocalDataMessage: "Это удалит локально сохранённые данные приложения на этом устройстве.",

        .backgroundLocation: "Локация (фон)",
        .backgroundLocationFooter: "Для стабильной работы GPS в фоне iOS требует разрешение Всегда. При включеном режиме Только при использовании фон может быть ограничен системой.",
        .gpsDeniedTitle: "GPS не разрешён",
        .gpsDeniedMessage: "GPS запрещён в настройках iOS (режим «Никогда» или ограничения). Разрешите доступ к геопозиции, иначе телеметрия и поездки могут не записываться.",
        .openIOSSettings: "Открыть настройки iOS",
        .alwaysRequiredTitle: "Для работы приложения в фоне требуется изменить разрешние на Всегда",
        .alwaysRequiredMessage: "Сейчас разрешение: При использовании. В фоне iOS может ограничивать обновления, и поездка/скоринг будут неточными.",
        .requestAlways: "Открыть настройки iOS и Запросить Всегда",
        .locationPermissionRequiredTitle: "Требуется разрешение на геолокацию",
        .locationPermissionRequiredMessage: "Разрешите доступ к геолокации, чтобы записывать телеметрию. Для работы в фоне потребуется выбрать опцию Всегда.",
        .allowLocation: "Разрешить геолокацию",
        .tripRecordingInProgress: "Идёт запись поездки",
        .readyToStartTrip: "Готово к началу поездки",
        
        .change: "Изменить",
     
        .gps: "GPS",
        .unstableOperationTitle: "Возможна некорректная работа",
        .alwaysPermissionHint: "Для стабильной записи поездки в фоне включите разрешение Всегда (Настройки → Геолокация).",
        .tripTime: "Время поездки",
        .distance: "Дистанция",
        .server: "Сервер",
        .deviceShort: "Устр.",
        .saveFishGame: "Игра Спаси Рыбку",
        .monitoring: "Мониторинг",
        .activity: "Активность",
        .state: "Состояние",
        .tripsToday: "Поездок сегодня",
        .dayMonitoringNote: "Примечание: iOS не различает личный авто и общественный транспорт на уровне activity. Сейчас детектируем только automotive; классификацию добавим следующим этапом.",
        .viewTripHistory: "Смотреть архив поездок",
        .offlineFinishMessage: "Поездка завершена успешно.\nОтчёты поездки появятся после восстановления связи с сервером.",
        .searchingServerMessage: "Завершение поездки. Ищем сервер Telemetry…",
        .autoFinishSearchingMessage: "Поездка авто-завершена. Завершаем и получаем отчёт…",
        .autoFinished: "Поездка авто-завершена",
        .tripFinishingGettingReport: "Поездка завершена. Получаем отчёт…",
        .driverAuthUnavailable: "Не удалось проверить ID водителя: EU/RU временно недоступны",
        .enableMonitoring: "Включить мониторинг",
        .disableMonitoring: "Выключить мониторинг",
        .driver: "Водитель",

        .continueButton: "Продолжить",
        .password: "Пароль",
        .create: "Создать",
        .signIn: "Войти",
        .back: "Назад",
        .checking: "Проверяем…",
        
        .driverLoginMissing: "Не задан логин водителя",
        
        .report: "Отчёт",
        .reportLoading: "Загрузка отчёта…",
        .reportLoadError: "Ошибка загрузки отчёта",
        
        .preliminaryReport: "Отчёт предварительный",
        .batchData: "Данные по батчам",
        .sent: "Отправлено",
        .notSent: "Не отправлено",
        .total: "Всего",
        .serverProcessing: "Сервер ещё обрабатывает",
        .autoFinishLabel: "Завершение: Авто",
        .drivingMode: "Режим поездки",
        .drivingLoad: "Интенсивность вождения",
        .yourAverageRating: "Ваш средний рейтинг",
        .countedTripsYouHave: "Учитываемых поездок у вас",
        .comparisonUnavailable: "Сравнение пока недоступно",
        .eventSummary: "Сводка событий",
        .dangerousManeuvers: "Опасные манёвры",
        .skidRisk: "Риск заноса",
        .roadAnomalies: "Неровности",
        .detailsV2: "Что повлияло на оценку",
        .details: "Подробно",
        .poor: "Плохо",
        .normal: "Нормально",
        .good: "Хорошо",
        .needsMoreCare: "Нужно аккуратнее",
        .someSharpMoments: "Есть резкие моменты",
        .almostPerfect: "Почти идеально",
        .outOf: "из",
        .driversGenitive: "водителей",
        .betterThanPrevTripsPrefix: "Лучше, чем",
        .betterThanPrevTripsSuffix: "ваших предыдущих поездок",
        .betterThanAllTripsPrefix: "Лучше, чем",
        .betterThanAllTripsSuffix: "поездок всех водителей",
        .totalTripsCounted: "Всего учтено поездок",
        .tripReportTitle: "Отчёт о поездке",
        
        .yourTrip: "Ваша поездка",
        .totals: "Итоги",
        .stops: "Остановки",
        .comparison: "Сравнение",
        .startLabel: "Старт",
        .finishLabel: "Финиш",
        .meters: "м",
        .vsPreviousTrip: "Лучше ваших предыдущих поездок",
        .vsAllTrips: "Лучше всех поездок всех водителей",
        .previousTripsDriver: "Поездок ранее (этот водитель)",
        .allTripsInDatabase: "Всего поездок (в базе)",
        .driverRank: "Рейтинг этого водителя",
        .totalDrivers: "Всего водителей",
        .driverAverageScore: "Средний оценка этого водителя",
        .driverTripsCount: "Поездок у водителя",
        
        .drivingModeMixed: "Смешанный",
        .drivingModeCity: "Город",
        .drivingModeHighway: "Трасса",
        .drivingModeUnknown: "Не определён",
  
        
        .stopsCount: "Количество остановок",
        .stopsTotal: "Общее время остановок",
        .stopsP95: "Длительность остановки (P95)",
        .stopsPerKm: "Остановок на км",
        .seconds: "сек",
        
        .eventClassesV2: "Классы событий",
        .eventClassSharpHelp: "• sharp — резкое действие. Есть риск, но обычно контролируемо.",
        .eventClassEmergencyHelp: "• emergency — экстренное действие. Резче порога, выше риск.",
        .eventClassAccelBrakeTurnHelp: "• accel/brake/turn — опасные маневры -по проекциям ускорения (a_long_g / a_lat_g).",
        .eventClassAccelBrakeInTurnHelp: "• accel_in_turn/brake_in_turn — риск заноса - комбинация продольного и поперечного ускорения (риск заноса).",
        .eventClassRoadAnomalyHelp: "• неровности — вертикальные пики (a_vert_g) + оценка severity.",
        .eventClassesImportantNote: "Важно: итоговая «опасность» зависит от скорости — скоринг учитывает speed_m_s.",
        .glassGameRunning: "Как плавно вы водите?",
        .glassGameOver: "Игра остановлена.\nВы пролили весь стакан",
        .glassGameSpilled: "Всего разлили:",
        .glassGameBonus: "Получили бонусом:",
        .glassGameHint: "Осторожно передвигайте стакан — вода реагирует на движения и разливается! Рыбка может погибнуть",
        .glassGameSpilledShort: "Пролито:",
        .dashcamTeaserMessage:
        "В версии 2.0 мы вас удивим здесь.\nНе пропустите новый релиз приложения.",
        .currentSpeed: "Текущая скорость",
        
        .accelerationSharp: "Ускорения (резкие)",
        .accelerationEmergency: "Ускорения (экстренные)",
        .brakingSharp: "Торможения (резкие)",
        .brakingEmergency: "Торможения (экстренные)",
        .turnsSharp: "Повороты (резкие)",
        .turnsEmergency: "Повороты (экстренные)",
        .accelerationInTurn: "Ускорение в повороте",
        .brakingInTurn: "Торможение в повороте",
        .roadAnomaliesLow: "Неровности (низкие)",
        .roadAnomaliesHigh: "Неровности (сильные)",
        
        .yourDrivingLevelToday: "Ваш уровень сегодня:",
        .betterThanDriversPercent: "лучше, чем у %d%% водителей",
        .topDriversPercent: "Топ %d%% водителей",
        
        .currentDrivingLevel: "Текущий уровень вождения:",
        .scoreDeltaLastTrips: "%@ за последние 5 поездок",
        .ratingFormingTripsLeft: "Рейтинг формируется — нужно ещё %d поездок",
        .toNextLevelLeft: "До уровня %@ осталось %@",
        .missingDeviceId: "Отсутствует ID устройства",

        .driverLevelRisky: "Рискованный водитель",
        .driverLevelAverage: "Спокойный водитель",
        .driverLevelSafe: "Уверенный водитель",
        .driverLevelPro: "Профессиональный водитель",
        
        .lastFiveTripsTitle: "Последние 5 поездок",
        .excellentSeriesFiveOfFive: "Отличная серия: 5 из 5",
        .goodSeriesFourOfFive: "Хорошая серия: 4 из 5",
        .decentSeriesThreeOfFive: "Неплохая серия: 3 из 5",
        .tripCanBeImproved: "Есть поездка, которую можно улучшить",
        .keepGreenSeriesNextTrip: "Сохраните зелёную серию в следующей поездке",
        .restoreGreenSeriesNextTrip: "Попробуйте вернуть зелёную серию уже в следующей поездке",
        .retry: "Повторить",
        
        .privacyPolicy: "Политика конфиденциальности",
        .termsOfUse: "Условия использования",

        .account: "Аккаунт",
        .deleteAccount: "Удалить аккаунт",
        .deleteAccountTitle: "Удалить аккаунт?",
        .deleteAccountMessage: "Это навсегда удалит ваш аккаунт и связанные данные приложения, которые мы не обязаны хранить.",
        .unableToDeleteAccount: "Не удалось удалить аккаунт",
        .accountNotFound: "Аккаунт не найден",
        .errorGeneric: "Произошла ошибка",
        .ok: "ОК",

        .changeDriverDuringTripTitle: "Изменить водителя во время активной поездки?",
        .changeDriverDuringTripMessage: "Текущая поездка будет остановлена и завершена с текущим ID водителя. После этого вы сможете войти с новым ID водителя.",

        .onboardingTitle: "Водите безопаснее и умнее",
        .onboardingAutoDetect: "Автоматически определяйте поездки",
        .onboardingSummary: "Смотрите сводку поездки и оценку вождения",
        .onboardingEvents: "Определяйте торможения, ускорения и повороты",
        .onboardingBackground: "Сохраняйте надёжную запись поездки в фоне",
        .onboardingPermissionText: "Мы запрашиваем доступ к геолокации и движению только для записи поездок, определения событий вождения и расчёта вашей оценки вождения.",

        .crashDetected: "Обнаружен удар",
        .crashImpactFormat: "Удар %.2f g",
       
        .deviceConfirmationFailed: "Не удалось подтвердить устройство. Используйте реальное устройство.",
        .loginFailedTryAgain: "Не удалось выполнить вход. Попробуйте снова.",
        
        .invalidPassword: "Неверный пароль",
        
        .archiveNotFound: "Архив поездок не найден",
        .archiveLoadFailedGeneric: "Не удалось загрузить архив поездок",
      
        
        .enterDriverId: "Изменить имя пользователя",
        .enterDriverIdButton: "Изменить имя пользователя",
        .driverIdRequired: "Имя пользователя создаётся автоматически",
        .driverIdSection: "Имя пользователя",
        .changeDriverId: "Изменить имя пользователя",
        .passwordConfirmationRequired: "Для этого имени пользователя на данном устройстве требуется пароль",
        .driverIdSetupDescription: "При первом запуске имя пользователя создаётся автоматически. Здесь его можно изменить, если вы хотите использовать свой профиль.",
        .driverId: "Имя пользователя",
        .newDriverPasswordPrompt: "Такого имени пользователя ещё нет. Задайте пароль, чтобы создать его.",
        .existingDriverPasswordPrompt: "Это имя пользователя уже существует. Введите пароль, чтобы использовать его на этом устройстве.",
        .serverStillRequiresPassword: "Сервер всё ещё требует пароль для этого имени пользователя на данном устройстве.",
        .driverIdNotCreatedOnServer: "Имя пользователя не было создано на сервере.",
        .driverIdNotFound: "Имя пользователя не найдено",
        .deviceNotAuthorizedForDriver: "Это устройство не авторизовано для данного имени пользователя",
        .videoArchiveTitle: "Архив видео",
        .videoArchiveLockedMessage: "Во время видеозаписи просмотр и удаление записей временно недоступны.",
        .crashRecordsSection: "Записи аварий",
        .closeButton: "Закрыть",
        .deselectAll: "Снять всё",
        .selectAll: "Выбрать всё",
        .deleteSelectedNormalTitle: "Удалить выбранные обычные записи?",
        .noButton: "Нет",
        .yesButton: "Да",
        .recordsDeleteIrreversible: "Записи будут удалены без возможности восстановления.",
        .deleteCrashRecordsTitle: "Удалить аварийные записи?",
        .crashDeleteFirstConfirm: "Аварийные записи хранятся отдельно. Это первое подтверждение удаления.",
        .confirmDeleteCrashRecordsTitle: "Подтвердите удаление аварийных записей",
        .crashRecordsDeleteIrreversible: "Аварийные записи будут удалены без возможности восстановления.",
        .archiveUnavailableDuringRecordingTitle: "Архив недоступен во время записи",
        .stopVideoRecordingToOpenArchive: "Остановите видеозапись, чтобы открыть просмотр или удаление записей.",
        .fileUnavailableTitle: "Файл недоступен",
        .unableToOpenRecordingMissingSegment: "Не удалось открыть запись. Возможно, файл сегмента отсутствует.",
        .saveToLibraryTitle: "Сохранить в медиатеку?",
        .saveToLibraryConfirmFormat: "Вы хотите сохранить %d записей общим размером %@ МБ?",
        .saveCompletedTitle: "Сохранение завершено",
        .readyShort: "Готово.",
        .totalRecordsFormat: "Всего записей: %d",
        .usedStorageFormat: "Использовано: %.2f ГБ (%d%%)",
        .recordsSavedInTwoMinuteFragments: "Записи сохраняются фрагментами по 2 минуты",
        .recordingMayContainSeveralFragments: "Одна запись может состоять из нескольких фрагментов в архиве",
        .reducesDeviceLoad: "Это сделано для снижения нагрузки на устройство",
        .archiveEmpty: "Архив пуст",
        .archiveEmptyDescription: "После записи видео здесь появятся обычные и аварийные ролики.",
        .summary: "Сводка",
        .normalRecords: "Обычные записи",
        .crashRecords: "Аварийные записи",
        .selected: "Выбрано",
        .all: "Все",
        .crashFilter: "Аварийные",
        .normalFilter: "Обычные",
        .segmentFormat: "Сегмент %d",
        .crashBadge: "АВАРИЯ",
        .savedBadge: "СОХРАНЕНО",
        .recordingFragmentFormat: "Запись №%d · Фрагмент %d",
        .durationLabelFormat: "Длительность: %@",
        .sizeGBFormat: "Размер: %.2f ГБ",
        .saveToMediaLibrary: "Сохранить в медиатеку",
        .deleteNormal: "Удалить обычные",
        .deleteCrash: "Удалить аварийные",
        .archiveFooterHint: "Можно выбрать записи и сохранить их в медиатеку. Для аварийных записей удаление требует двойного подтверждения.",
        .videoRecordingInProgress: "Идёт видеозапись",
        .videoSavingInProgress: "Идёт сохранение записи",
        .hideCamera: "Скрыть камеру",
        .showCamera: "Показать камеру",
        .stopVideo: "Стоп видео",
        .camera: "Камера",
        .roadCamera: "Дорога",
        .driverCamera: "Водитель",

        .dmsAlertCriticalTitle: "ВОДИТЕЛЬ ЗАСЫПАЕТ",
        .dmsAlertCriticalSubtitle: "СРОЧНО ОСТАНОВИТЕСЬ",
        .dmsAlertWarning: "Признаки усталости водителя",
        .dmsAlertDrowsy: "Голова опущена",
        .dmsAlertDistracted: "Смотрите на дорогу",

        .smoothness: "Плавность",
        
        .recordingTitleFormat: "Запись №%d",
        .savedToLibraryFormat: "Сохранено в медиатеку: %d",        
        
        .onboardingDashcamTitle: "Видеорегистратор в поездках",
        .onboardingDashcamVideoRecording: "Видео записывается во время поездки",
        .onboardingDashcamForegroundOnly: "Приложение должно быть открыто на экране",
        .onboardingDashcamNoHiddenBackground: "Запись не работает как скрытый фоновый режим",
        .onboardingDashcamFooter: "Видеорежим показывает статус записи, таймер и управляющие кнопки.",

        .onboardingCrashTitle: "Аварийные клипы",
        .onboardingCrashProtectedClip: "При резком ударе сохраняется защищённый клип",
        .onboardingCrashBeforeAfter: "Сохраняются секунды до и после события",
        .onboardingCrashNotAutoDeleted: "Аварийные записи не удаляются автоматически",
        .onboardingCrashFooter: "Клип аварии помогает связать видео, координаты, скорость и телеметрию поездки.",

        .onboardingPermissionsTitle: "Разрешения",
        .onboardingPermissionCamera: "Камера нужна для записи видео",
        .onboardingPermissionMicrophone: "Микрофон используется только если включена запись звука",
        .onboardingPermissionPhotoLibrary: "Выбранные записи можно сохранить в медиатеку вручную",
        .onboardingPermissionsFooter: "Перед началом видеорежима приложение запросит необходимые разрешения.",

        .nextButton: "Далее",
        .tripConfigHelpSpeedGateAccelBrakeMsTitle: "Гейт скорости для accel/brake",
        .tripConfigHelpSpeedGateAccelBrakeMsBody: "Минимальная скорость, ниже которой события разгона и торможения не фиксируются.",
        .tripConfigHelpSpeedGateAccelBrakeMsMore: "Больше → меньше событий на низкой скорости, но резкий манёвр на малой скорости может быть пропущен.",
        .tripConfigHelpSpeedGateAccelBrakeMsLess: "Меньше → больше событий на низкой скорости, больше шума и ложных срабатываний.",
        .tripConfigHelpSpeedGateTurnMsTitle: "Гейт скорости для поворотов",
        .tripConfigHelpSpeedGateTurnMsBody: "Минимальная скорость, ниже которой повороты не фиксируются.",
        .tripConfigHelpSpeedGateTurnMsMore: "Больше → меньше поворотов на малой скорости и меньше шума.",
        .tripConfigHelpSpeedGateTurnMsLess: "Меньше → больше поворотов на малой скорости и выше риск ложных срабатываний.",
        .tripConfigHelpSpeedGateCombinedMsTitle: "Гейт скорости для combined events",
        .tripConfigHelpSpeedGateCombinedMsBody: "Минимальная скорость, ниже которой комбинированные события не фиксируются.",
        .tripConfigHelpSpeedGateCombinedMsMore: "Больше → меньше комбинированных событий на малой скорости.",
        .tripConfigHelpSpeedGateCombinedMsLess: "Меньше → больше комбинированных событий на малой скорости и больше шума.",
        .tripConfigHelpCooldownAccelBrakeSTitle: "Cooldown accel/brake",
        .tripConfigHelpCooldownAccelBrakeSBody: "Минимальный интервал между событиями разгона или торможения.",
        .tripConfigHelpCooldownAccelBrakeSMore: "Больше → меньше повторных событий.",
        .tripConfigHelpCooldownAccelBrakeSLess: "Меньше → больше повторных событий и выше риск дублей.",
        .tripConfigHelpCooldownTurnSTitle: "Cooldown turn",
        .tripConfigHelpCooldownTurnSBody: "Минимальный интервал между событиями поворота.",
        .tripConfigHelpCooldownTurnSMore: "Больше → меньше повторных поворотов.",
        .tripConfigHelpCooldownTurnSLess: "Меньше → больше событий поворота во время одного длинного манёвра.",
        .tripConfigHelpCooldownCombinedSTitle: "Cooldown combined",
        .tripConfigHelpCooldownCombinedSBody: "Минимальный интервал между комбинированными событиями.",
        .tripConfigHelpCooldownCombinedSMore: "Больше → меньше комбинированных событий.",
        .tripConfigHelpCooldownCombinedSLess: "Меньше → комбинированные события могут фиксироваться чаще.",
        .tripConfigHelpCooldownRoadSTitle: "Cooldown неровностей",
        .tripConfigHelpCooldownRoadSBody: "Минимальный интервал между событиями неровностей дороги.",
        .tripConfigHelpCooldownRoadSMore: "Больше → меньше повторов на кочках.",
        .tripConfigHelpCooldownRoadSLess: "Меньше → больше событий на плохой дороге.",
        .tripConfigHelpAccelSharpGTitle: "Порог резкого разгона",
        .tripConfigHelpAccelSharpGBody: "Порог продольного ускорения для резкого разгона.",
        .tripConfigHelpAccelSharpGMore: "Больше → резкий разгон фиксируется реже.",
        .tripConfigHelpAccelSharpGLess: "Меньше → резкий разгон фиксируется чаще.",
        .tripConfigHelpAccelEmergencyGTitle: "Порог экстренного разгона",
        .tripConfigHelpAccelEmergencyGBody: "Порог продольного ускорения для экстренного разгона.",
        .tripConfigHelpAccelEmergencyGMore: "Больше → экстренный разгон фиксируется редко.",
        .tripConfigHelpAccelEmergencyGLess: "Меньше → экстренный разгон фиксируется чаще.",
        .tripConfigHelpBrakeSharpGTitle: "Порог резкого торможения",
        .tripConfigHelpBrakeSharpGBody: "Порог продольного замедления для резкого торможения.",
        .tripConfigHelpBrakeSharpGMore: "Больше → резкое торможение фиксируется реже.",
        .tripConfigHelpBrakeSharpGLess: "Меньше → резкое торможение фиксируется чаще.",
        .tripConfigHelpBrakeEmergencyGTitle: "Порог экстренного торможения",
        .tripConfigHelpBrakeEmergencyGBody: "Порог продольного замедления для экстренного торможения.",
        .tripConfigHelpBrakeEmergencyGMore: "Больше → экстренное торможение фиксируется редко.",
        .tripConfigHelpBrakeEmergencyGLess: "Меньше → экстренное торможение фиксируется чаще.",
        .tripConfigHelpTurnSharpLatGTitle: "Порог резкого поворота",
        .tripConfigHelpTurnSharpLatGBody: "Порог бокового ускорения для резких поворотов.",
        .tripConfigHelpTurnSharpLatGMore: "Больше → резкие повороты фиксируются реже.",
        .tripConfigHelpTurnSharpLatGLess: "Меньше → резкие повороты фиксируются чаще.",
        .tripConfigHelpTurnEmergencyLatGTitle: "Порог экстренного поворота",
        .tripConfigHelpTurnEmergencyLatGBody: "Порог бокового ускорения для экстренных поворотов.",
        .tripConfigHelpTurnEmergencyLatGMore: "Больше → экстренные повороты фиксируются редко.",
        .tripConfigHelpTurnEmergencyLatGLess: "Меньше → экстренные повороты фиксируются чаще.",
        .tripConfigHelpCombinedLatMinGTitle: "Минимальный lateral g для combined events",
        .tripConfigHelpCombinedLatMinGBody: "Комбинированные события фиксируются только выше этого бокового ускорения.",
        .tripConfigHelpCombinedLatMinGMore: "Больше → меньше комбинированных событий.",
        .tripConfigHelpCombinedLatMinGLess: "Меньше → больше комбинированных событий.",
        .tripConfigHelpAccelInTurnSharpGTitle: "Порог резкого разгона в повороте",
        .tripConfigHelpAccelInTurnSharpGBody: "Порог продольного ускорения для резкого разгона в повороте.",
        .tripConfigHelpAccelInTurnSharpGMore: "Больше → меньше событий.",
        .tripConfigHelpAccelInTurnSharpGLess: "Меньше → больше событий.",
        .tripConfigHelpAccelInTurnEmergencyGTitle: "Порог экстренного разгона в повороте",
        .tripConfigHelpAccelInTurnEmergencyGBody: "Порог продольного ускорения для экстренного разгона в повороте.",
        .tripConfigHelpAccelInTurnEmergencyGMore: "Больше → редкие экстренные события.",
        .tripConfigHelpAccelInTurnEmergencyGLess: "Меньше → больше экстренных событий.",
        .tripConfigHelpBrakeInTurnSharpGTitle: "Порог резкого торможения в повороте",
        .tripConfigHelpBrakeInTurnSharpGBody: "Порог продольного замедления для резкого торможения в повороте.",
        .tripConfigHelpBrakeInTurnSharpGMore: "Больше → меньше событий.",
        .tripConfigHelpBrakeInTurnSharpGLess: "Меньше → больше событий.",
        .tripConfigHelpBrakeInTurnEmergencyGTitle: "Порог экстренного торможения в повороте",
        .tripConfigHelpBrakeInTurnEmergencyGBody: "Порог продольного замедления для экстренного торможения в повороте.",
        .tripConfigHelpBrakeInTurnEmergencyGMore: "Больше → редкие экстренные события.",
        .tripConfigHelpBrakeInTurnEmergencyGLess: "Меньше → больше экстренных событий.",
        .tripConfigHelpRoadWindowSTitle: "Окно анализа неровностей",
        .tripConfigHelpRoadWindowSBody: "Длительность окна для расчёта пиков вертикального ускорения.",
        .tripConfigHelpRoadWindowSMore: "Больше → более сглаженное детектирование.",
        .tripConfigHelpRoadWindowSLess: "Меньше → более чувствительное детектирование.",
        .tripConfigHelpRoadLowP2pGTitle: "Порог low p2p неровностей",
        .tripConfigHelpRoadLowP2pGBody: "Порог vertical peak-to-peak для слабой неровности.",
        .tripConfigHelpRoadLowP2pGMore: "Больше → меньше low events.",
        .tripConfigHelpRoadLowP2pGLess: "Меньше → больше low events.",
        .tripConfigHelpRoadHighP2pGTitle: "Порог high p2p неровностей",
        .tripConfigHelpRoadHighP2pGBody: "Порог vertical peak-to-peak для сильной неровности.",
        .tripConfigHelpRoadHighP2pGMore: "Больше → меньше high events.",
        .tripConfigHelpRoadHighP2pGLess: "Меньше → больше high events.",
        .tripConfigHelpRoadLowAbsGTitle: "Порог low max неровностей",
        .tripConfigHelpRoadLowAbsGBody: "Порог максимального вертикального ускорения для слабой неровности.",
        .tripConfigHelpRoadLowAbsGMore: "Больше → меньше low events.",
        .tripConfigHelpRoadLowAbsGLess: "Меньше → больше low events.",
        .tripConfigHelpRoadHighAbsGTitle: "Порог high max неровностей",
        .tripConfigHelpRoadHighAbsGBody: "Порог максимального вертикального ускорения для сильной неровности.",
        .tripConfigHelpRoadHighAbsGMore: "Больше → меньше high events.",
        .tripConfigHelpRoadHighAbsGLess: "Меньше → больше high events.",
        .tripConfigHelpDoubleCountWindowSTitle: "Окно подавления double count",
        .tripConfigHelpDoubleCountWindowSBody: "Окно для подавления обычных событий рядом с комбинированными.",
        .tripConfigHelpDoubleCountWindowSMore: "Больше → сильнее подавление дублей.",
        .tripConfigHelpDoubleCountWindowSLess: "Меньше → combined и обычные события чаще считаются вместе.",
        .tripConfigHelpSpeedBreakpointsMsTitle: "Speed factor breakpoints",
        .tripConfigHelpSpeedBreakpointsMsBody: "Точки скорости для интерполяции speed factor.",
        .tripConfigHelpSpeedBreakpointsMsMore: "Более высокие значения могут усилить штрафы на высокой скорости.",
        .tripConfigHelpSpeedBreakpointsMsLess: "Более низкие значения смягчают рост штрафа от скорости.",
        .tripConfigHelpSpeedFactorsTitle: "Speed factors",
        .tripConfigHelpSpeedFactorsBody: "Коэффициенты speed factor для соответствующих точек скорости.",
        .tripConfigHelpSpeedFactorsMore: "Больше → сильнее штрафы на этих скоростях.",
        .tripConfigHelpSpeedFactorsLess: "Меньше → слабее штрафы на этих скоростях.",
        .tripConfigHelpPenaltyAccelSharpTitle: "Штраф за резкий разгон",
        .tripConfigHelpPenaltyAccelSharpBody: "Базовый штраф за резкий разгон.",
        .tripConfigHelpPenaltyAccelSharpMore: "Больше → сильнее снижение score.",
        .tripConfigHelpPenaltyAccelSharpLess: "Меньше → слабее снижение score.",
        .tripConfigHelpPenaltyAccelEmergencyTitle: "Штраф за экстренный разгон",
        .tripConfigHelpPenaltyAccelEmergencyBody: "Базовый штраф за экстренный разгон.",
        .tripConfigHelpPenaltyAccelEmergencyMore: "Больше → сильнее снижение score.",
        .tripConfigHelpPenaltyAccelEmergencyLess: "Меньше → слабее снижение score.",
        .tripConfigHelpPenaltyBrakeSharpTitle: "Штраф за резкое торможение",
        .tripConfigHelpPenaltyBrakeSharpBody: "Базовый штраф за резкое торможение.",
        .tripConfigHelpPenaltyBrakeSharpMore: "Больше → сильнее снижение score.",
        .tripConfigHelpPenaltyBrakeSharpLess: "Меньше → слабее снижение score.",
        .tripConfigHelpPenaltyBrakeEmergencyTitle: "Штраф за экстренное торможение",
        .tripConfigHelpPenaltyBrakeEmergencyBody: "Базовый штраф за экстренное торможение.",
        .tripConfigHelpPenaltyBrakeEmergencyMore: "Больше → сильнее снижение score.",
        .tripConfigHelpPenaltyBrakeEmergencyLess: "Меньше → слабее снижение score.",
        .tripConfigHelpPenaltyTurnSharpTitle: "Штраф за резкий поворот",
        .tripConfigHelpPenaltyTurnSharpBody: "Базовый штраф за резкий поворот.",
        .tripConfigHelpPenaltyTurnSharpMore: "Больше → сильнее снижение score.",
        .tripConfigHelpPenaltyTurnSharpLess: "Меньше → слабее снижение score.",
        .tripConfigHelpPenaltyTurnEmergencyTitle: "Штраф за экстренный поворот",
        .tripConfigHelpPenaltyTurnEmergencyBody: "Базовый штраф за экстренный поворот.",
        .tripConfigHelpPenaltyTurnEmergencyMore: "Больше → сильнее снижение score.",
        .tripConfigHelpPenaltyTurnEmergencyLess: "Меньше → слабее снижение score.",
        .tripConfigHelpPenaltyAccelInTurnSharpTitle: "Штраф за резкий разгон в повороте",
        .tripConfigHelpPenaltyAccelInTurnSharpBody: "Базовый штраф за резкий разгон в повороте.",
        .tripConfigHelpPenaltyAccelInTurnSharpMore: "Больше → сильнее снижение score.",
        .tripConfigHelpPenaltyAccelInTurnSharpLess: "Меньше → слабее снижение score.",
        .tripConfigHelpPenaltyAccelInTurnEmergencyTitle: "Штраф за экстренный разгон в повороте",
        .tripConfigHelpPenaltyAccelInTurnEmergencyBody: "Базовый штраф за экстренный разгон в повороте.",
        .tripConfigHelpPenaltyAccelInTurnEmergencyMore: "Больше → сильнее снижение score.",
        .tripConfigHelpPenaltyAccelInTurnEmergencyLess: "Меньше → слабее снижение score.",
        .tripConfigHelpPenaltyBrakeInTurnSharpTitle: "Штраф за резкое торможение в повороте",
        .tripConfigHelpPenaltyBrakeInTurnSharpBody: "Базовый штраф за резкое торможение в повороте.",
        .tripConfigHelpPenaltyBrakeInTurnSharpMore: "Больше → сильнее снижение score.",
        .tripConfigHelpPenaltyBrakeInTurnSharpLess: "Меньше → слабее снижение score.",
        .tripConfigHelpPenaltyBrakeInTurnEmergencyTitle: "Штраф за экстренное торможение в повороте",
        .tripConfigHelpPenaltyBrakeInTurnEmergencyBody: "Базовый штраф за экстренное торможение в повороте.",
        .tripConfigHelpPenaltyBrakeInTurnEmergencyMore: "Больше → сильнее снижение score.",
        .tripConfigHelpPenaltyBrakeInTurnEmergencyLess: "Меньше → слабее снижение score.",
        .tripConfigHelpPenaltyRoadLowTitle: "Штраф за слабую неровность",
        .tripConfigHelpPenaltyRoadLowBody: "Базовый штраф за слабую неровность.",
        .tripConfigHelpPenaltyRoadLowMore: "Больше → сильнее снижение score.",
        .tripConfigHelpPenaltyRoadLowLess: "Меньше → слабее снижение score.",
        .tripConfigHelpPenaltyRoadHighTitle: "Штраф за сильную неровность",
        .tripConfigHelpPenaltyRoadHighBody: "Базовый штраф за сильную неровность.",
        .tripConfigHelpPenaltyRoadHighMore: "Больше → сильнее снижение score.",
        .tripConfigHelpPenaltyRoadHighLess: "Меньше → слабее снижение score.",
        .crashTitleWithDateFormat: "АВАРИЯ %@",

        .dmsVoiceEyesClosed: "Глаза закрыты!",
        .dmsVoiceHeadDown: "Голова опущена!",
        .dmsVoiceDistractedLeft: "Голова смотрит влево! Смотрите на дорогу!",
        .dmsVoiceDistractedRight: "Голова смотрит вправо! Смотрите на дорогу!",
        .dmsVoiceYawning: "Водитель зевает!",
        .dmsVoiceFaceLost: "Лицо не видно! Смотрите на дорогу!",
        .dmsVoiceEmergencyStop: "Срочно останови-тесь!",
                    
            
        
    ]

    // Пока пустые
    static let spanish: [LocalizationKey: String] = [:]
    static let french: [LocalizationKey: String] = [:]
    static let chineseSimplified: [LocalizationKey: String] = [:]
    static let hindi: [LocalizationKey: String] = [:]
}


extension LocalizationCatalog {
    static var currentLanguage: AppLanguage {
        if let rawLanguage = UserDefaults.standard.string(forKey: "app_language"),
           let storedLanguage = AppLanguage(rawValue: rawLanguage),
           AppLanguageRegistry.enabledInUI.contains(storedLanguage) {
            return storedLanguage
        }

        if let preferredLanguage = Locale.preferredLanguages.first,
           preferredLanguage.lowercased().hasPrefix("ru") {
            return .russian
        }

        return AppLanguage.fallback
    }

    static var currentLocale: Locale {
        Locale(identifier: currentLanguage.localeIdentifier)
    }

    static func text(_ key: LocalizationKey) -> String {
        if let value = catalog[currentLanguage]?[key] {
            return value
        }

        if let fallback = catalog[AppLanguage.fallback]?[key] {
            return fallback
        }

        return key.rawValue
    }
}
