//
//  LocalizationKey.swift
//  TelemetryApp
//
//  Created by Alex on 15.03.26.
//

import Foundation

enum LocalizationKey: String {

    // Common
    case done
    case close
    case cancel
    case loading
    case settings
    case language
    case openSettings

    // Home
    case driverScore
    case recording
    case ready
    case start
    case stop
    case tripHistory
    case dashcam

    // Driver
    case driverLabel
    case enterDriverId
    case enterDriverIdButton
    case driverIdRequired
    
    case driverIdSection
    case current
    case changeDriverId
    
    case privacy
    case privacyDescription
    case deleteLocalData
    
    case delete    
    case deleteLocalDataTitle
    case deleteLocalDataMessage
    

    // Archive
    case tripArchiveTitle
    case tripDate
    case score
    case km
    case kmh
    case noTripsInArchive
    case archiveLoadError

    // Trip Report
    case tripDuration
    case averageSpeed
    case notEnoughData
    case excellent
    case verySmooth
    
    case backgroundLocation
    case backgroundLocationFooter
    case gpsDeniedTitle
    case gpsDeniedMessage
    case openIOSSettings
    case alwaysRequiredTitle
    case alwaysRequiredMessage
    case requestAlways
    case locationPermissionRequiredTitle
    case locationPermissionRequiredMessage
    case allowLocation
    
    case tripRecordingInProgress
    case readyToStartTrip
    
    case change
    case passwordConfirmationRequired
    case gps
    case unstableOperationTitle
    case alwaysPermissionHint
    case tripTime
    case distance
    case server
    case deviceShort
    case saveFishGame
    case monitoring
    case activity
    case state
    case tripsToday
    case dayMonitoringNote
    case viewTripHistory
    case offlineFinishMessage
    case searchingServerMessage
    case autoFinishSearchingMessage
    case autoFinished
    case tripFinishingGettingReport
    case driverAuthUnavailable
    case enableMonitoring
    case disableMonitoring
    case driver
    case driverIdSetupDescription
    case continueButton
    case password
    case create
    case signIn
    case back
    case checking
    case newDriverPasswordPrompt
    case existingDriverPasswordPrompt
    case serverStillRequiresPassword
    case driverIdNotCreatedOnServer

    case driverLoginMissing

    case report
    case reportLoading
    case reportLoadError
    
    case preliminaryReport
    case batchData
    case sent
    case notSent
    case total
    case serverProcessing
    case autoFinishLabel
    case drivingMode
    case drivingLoad
    case yourAverageRating
    case countedTripsYouHave
    case comparisonUnavailable
    case eventSummary
    case dangerousManeuvers
    case skidRisk
    case roadAnomalies
    case detailsV2
    case details
    case poor
    case normal
    case good
    case needsMoreCare
    case someSharpMoments
    case almostPerfect
    case outOf
    case driversGenitive
    case betterThanPrevTripsPrefix
    case betterThanPrevTripsSuffix
    case betterThanAllTripsPrefix
    case betterThanAllTripsSuffix
    case totalTripsCounted
    case tripReportTitle
    
    case yourTrip
    case totals
    case stops
    case comparison
    case startLabel
    case finishLabel
    case meters
    case vsPreviousTrip
    case vsAllTrips
    case previousTripsDriver
    case allTripsInDatabase
    case driverRank
    case totalDrivers
    case driverAverageScore
    case driverTripsCount
    
    case drivingModeMixed
    case drivingModeCity
    case drivingModeHighway
    case drivingModeUnknown
    
    case seconds
    
    case stopsCount
    case stopsTotal
    case stopsP95
    case stopsPerKm
    
    case eventClassesV2
    case eventClassSharpHelp
    case eventClassEmergencyHelp
    case eventClassAccelBrakeTurnHelp
    case eventClassAccelBrakeInTurnHelp
    case eventClassRoadAnomalyHelp
    case eventClassesImportantNote
    
    case glassGameRunning
    case glassGameOver
    case glassGameSpilled
    case glassGameBonus
    case glassGameHint
    case glassGameSpilledShort
    
    case dashcamTeaserMessage
    
    case currentSpeed
    
    case accelerationSharp
    case accelerationEmergency
    case brakingSharp
    case brakingEmergency
    case turnsSharp
    case turnsEmergency
    case accelerationInTurn
    case brakingInTurn
    case roadAnomaliesLow
    case roadAnomaliesHigh
    
    case yourDrivingLevelToday
    case betterThanDriversPercent
    case topDriversPercent
    
    case currentDrivingLevel
    case scoreDeltaLastTrips
    case ratingFormingTripsLeft
    case toNextLevelLeft
    case missingDeviceId
    case driverLevelRisky
    case driverLevelAverage
    case driverLevelSafe
    case driverLevelPro
    
    case lastFiveTripsTitle
    case excellentSeriesFiveOfFive
    case goodSeriesFourOfFive
    case decentSeriesThreeOfFive
    case tripCanBeImproved
    case keepGreenSeriesNextTrip
    case restoreGreenSeriesNextTrip
    
    case retry
    
    case privacyPolicy
    case termsOfUse

    case account
    case deleteAccount
    case deleteAccountTitle
    case deleteAccountMessage
    case unableToDeleteAccount
    case accountNotFound
    case errorGeneric
    case ok

    case changeDriverDuringTripTitle
    case changeDriverDuringTripMessage

    case onboardingTitle
    case onboardingAutoDetect
    case onboardingSummary
    case onboardingEvents
    case onboardingBackground
    case onboardingPermissionText
    
    case onboardingDashcamTitle
    case onboardingDashcamVideoRecording
    case onboardingDashcamForegroundOnly
    case onboardingDashcamNoHiddenBackground
    case onboardingDashcamFooter

    case onboardingCrashTitle
    case onboardingCrashProtectedClip
    case onboardingCrashBeforeAfter
    case onboardingCrashNotAutoDeleted
    case onboardingCrashFooter

    case onboardingPermissionsTitle
    case onboardingPermissionCamera
    case onboardingPermissionMicrophone
    case onboardingPermissionPhotoLibrary
    case onboardingPermissionsFooter

    case nextButton

    case crashDetected
    case crashImpactFormat
    
    case driverId
    case deviceConfirmationFailed
    case loginFailedTryAgain
    
    case driverIdNotFound
    case invalidPassword
    
    case deviceNotAuthorizedForDriver
    case archiveNotFound
    case archiveLoadFailedGeneric
    
    case driverScoreOneTrip
    
    
    case videoArchiveTitle
    case videoArchiveLockedMessage
    case crashRecordsSection
    case closeButton
    case deselectAll
    case selectAll
    case deleteSelectedNormalTitle
    case noButton
    case yesButton
    case recordsDeleteIrreversible
    case deleteCrashRecordsTitle
    case crashDeleteFirstConfirm
    case confirmDeleteCrashRecordsTitle
    case crashRecordsDeleteIrreversible
    case archiveUnavailableDuringRecordingTitle
    case stopVideoRecordingToOpenArchive
    case fileUnavailableTitle
    case unableToOpenRecordingMissingSegment
    case saveToLibraryTitle
    case saveToLibraryConfirmFormat
    case saveCompletedTitle
    case readyShort
    case totalRecordsFormat
    case usedStorageFormat
    case recordsSavedInTwoMinuteFragments
    case recordingMayContainSeveralFragments
    case reducesDeviceLoad
    case archiveEmpty
    case archiveEmptyDescription
    case summary
    case normalRecords
    case crashRecords
    case selected
    case all
    case crashFilter
    case normalFilter
    case segmentFormat
    case crashBadge
    case savedBadge
    case recordingFragmentFormat
    case durationLabelFormat
    case sizeGBFormat
    case saveToMediaLibrary
    case deleteNormal
    case deleteCrash
    case archiveFooterHint
    case videoRecordingInProgress
    case videoSavingInProgress
    case hideCamera
    case showCamera
    case stopVideo
    case smoothness
    case recordingTitleFormat
    case savedToLibraryFormat
    case crashTitleWithDateFormat
    
    case dmsVoiceEyesClosed
    case dmsVoiceHeadDown
    case dmsVoiceDistractedLeft
    case dmsVoiceDistractedRight
    case dmsVoiceYawning
    case dmsVoiceFaceLost
    case dmsVoiceEmergencyStop
    
    case camera
    case roadCamera
    case driverCamera

    case dmsAlertCriticalTitle
    case dmsAlertCriticalSubtitle
    case dmsAlertWarning
    case dmsAlertDrowsy
    case dmsAlertDistracted

    case english
    case russian
    case spanish
    case french
    case chineseSimplified
    case hindi
    case activityUnavailable
    case statusIdle
    case appIdle
    case telemetryModeImuOnly
    case alreadyStarted
    case enterDriverIdStatus
    case statusStarting
    case statusCollecting
    case statusRunningFormat
    case statusStopped
    case alreadyStopped
    case deviceMotionUnavailable
    case motionErrorFormat
    case statusRunningStabilizingFormat
    case statusRunningCalibrationFormat
    case locationNotRequested
    case dashcamBackgroundFinishFailed
    case dashcamResumeAfterInterruptionFailedFormat
    case dashcamUnknownCameraError
    case dashcamCameraErrorFormat
    case dashcamCameraRecoveryFailedFormat
    case dashcamBeginRecordingFailedFormat
    case dashcamRecordingStoppedInBackground
    case dashcamRecordingCouldNotContinueAfterForeground
    case dashcamSegmentTimeout
    case dashcamSystemInterruptedFormat
    case dashcamSegmentRestartFailedFormat
    case dashcamSegmentSaveFailedFormat
    case dashcamNextSegmentStartFailedFormat
    case dashcamAddCompletedSegmentFailed
    case tripConfigSavedStatusFormat
    case dashcamErrorCameraUnavailable
    case dashcamErrorMicrophoneUnavailable
    case dashcamErrorCameraPermissionDenied
    case dashcamErrorMicrophonePermissionDenied
    case dashcamErrorPhotoLibraryDenied
    case dashcamErrorCannotCreateSession
    case dashcamErrorCannotCreateOutput
    case dashcamErrorCannotStartRecording
    case dashcamErrorQuotaExceeded
    case dashcamErrorArchiveBlockedByCrashRecords
    case dashcamErrorInsufficientSpaceForNextSegment
    case dashcamErrorInterrupted
    case trackingModeSingleTrip
    case trackingModeDayMonitoring
    case developerIdentifiersSection
    case device
    case session
    case footnote
    case semibold
    case errorsSection
    case clearErrors
    case sensorThresholdSettings
    case tripConfigSectionGatesCooldowns
    case tripConfigSectionThresholds
    case tripConfigSectionScoring
    case tripConfigSectionScoringPenalty
    case tripConfigResetOverrides
    case tripConfigSaveForNextTrip
    case tripConfigStatusSection
    case tripConfigNeverSaved
    case tripConfigNavigationTitle
    case tripConfigSavedAlertTitle
    case tripConfigSavedForNextTrip
    case subheadline
    case tripConfigManualOverride
    case tripConfigValuePlaceholder
    case tripConfigDefaultValue
    case tripConfigCsvPlaceholder
    case headline
    case tripConfigIfHigher
    case tripConfigIfLower
    case tripConfigMissingHelp
    case tripConfigHelpTitle
    case title2
    case bold
    case center
    case caption
    case body
    case tripIdFormat
    case caption2
    case dmsStateNormal
    case dmsStateWarning
    case dmsStateCritical
    case dmsStateDistracted
    case dmsStateDrowsy
    case statsColumnEvent
    case statsColumnCount
    case statsColumnSumG
    case statsColumnMaxG
    case statsColumnCountPerKm
    case statsColumnGPerKm
    case statsColumnHelpEvent
    case statsColumnHelpCount
    case statsColumnHelpSumG
    case statsColumnHelpMaxG
    case statsColumnHelpCountPerKm
    case statsColumnHelpGPerKm
    case red
    case dmsMonitoringTitle
    case dmsEyeScoreFormat
    case dmsFatigueLabel
    case dmsScoreMax
    case dmsPerclosFormat
    case dmsStateFormat
    case medium
    case indoorTestModeToggle
    case indoorTestModeDescription
    case maneuverTestModeToggle
    case maneuverTestTitle
    case maneuverTestDescription
    case projectedG
    case rotationRate
    case userAcceleration
    case lastEvent
    case statusLabel
    case lastFiveErrors
    case lastGps
    case speedKmhLabel
    case accelXyz
    case statsBraking
    case statsAcceleration
    case statsRoadAnomalies
    case statsTurns
    case statsSkid
    case title3
    case waitingServerData
    case exposureScore
    case preset
    case worstBatchScore
    case speedSection
    case speedMax
    case speedAverage
    case eventsInBatches
    case sensorsExtremesSection
    case dataTransferSection
    case maxBatchSeq
    case missingBatchSeq
    case sentBatchToEU
    case sentBatchViaRU
    case reportReceivedVia
    case gpsQualitySection
    case gpsAccuracyP95
    case metersSuffix
    case goodPoints100m
    case gpsStuck
    case yes
    case no
    case gpsQuality
    case uniqueCoordinates
    case coordinateSpread
    case identifiersSection
    case serverTimingSection
    case leading
    case trailing
    case videoSaveNothingSelected
    case videoSavePartialResultFormat
    case videoSaveToLibraryFailed

    case tripConfigHelpSpeedGateAccelBrakeMsTitle
    case tripConfigHelpSpeedGateAccelBrakeMsBody
    case tripConfigHelpSpeedGateAccelBrakeMsMore
    case tripConfigHelpSpeedGateAccelBrakeMsLess
    case tripConfigHelpSpeedGateTurnMsTitle
    case tripConfigHelpSpeedGateTurnMsBody
    case tripConfigHelpSpeedGateTurnMsMore
    case tripConfigHelpSpeedGateTurnMsLess
    case tripConfigHelpSpeedGateCombinedMsTitle
    case tripConfigHelpSpeedGateCombinedMsBody
    case tripConfigHelpSpeedGateCombinedMsMore
    case tripConfigHelpSpeedGateCombinedMsLess
    case tripConfigHelpCooldownAccelBrakeSTitle
    case tripConfigHelpCooldownAccelBrakeSBody
    case tripConfigHelpCooldownAccelBrakeSMore
    case tripConfigHelpCooldownAccelBrakeSLess
    case tripConfigHelpCooldownTurnSTitle
    case tripConfigHelpCooldownTurnSBody
    case tripConfigHelpCooldownTurnSMore
    case tripConfigHelpCooldownTurnSLess
    case tripConfigHelpCooldownCombinedSTitle
    case tripConfigHelpCooldownCombinedSBody
    case tripConfigHelpCooldownCombinedSMore
    case tripConfigHelpCooldownCombinedSLess
    case tripConfigHelpCooldownRoadSTitle
    case tripConfigHelpCooldownRoadSBody
    case tripConfigHelpCooldownRoadSMore
    case tripConfigHelpCooldownRoadSLess
    case tripConfigHelpAccelSharpGTitle
    case tripConfigHelpAccelSharpGBody
    case tripConfigHelpAccelSharpGMore
    case tripConfigHelpAccelSharpGLess
    case tripConfigHelpAccelEmergencyGTitle
    case tripConfigHelpAccelEmergencyGBody
    case tripConfigHelpAccelEmergencyGMore
    case tripConfigHelpAccelEmergencyGLess
    case tripConfigHelpBrakeSharpGTitle
    case tripConfigHelpBrakeSharpGBody
    case tripConfigHelpBrakeSharpGMore
    case tripConfigHelpBrakeSharpGLess
    case tripConfigHelpBrakeEmergencyGTitle
    case tripConfigHelpBrakeEmergencyGBody
    case tripConfigHelpBrakeEmergencyGMore
    case tripConfigHelpBrakeEmergencyGLess
    case tripConfigHelpTurnSharpLatGTitle
    case tripConfigHelpTurnSharpLatGBody
    case tripConfigHelpTurnSharpLatGMore
    case tripConfigHelpTurnSharpLatGLess
    case tripConfigHelpTurnEmergencyLatGTitle
    case tripConfigHelpTurnEmergencyLatGBody
    case tripConfigHelpTurnEmergencyLatGMore
    case tripConfigHelpTurnEmergencyLatGLess
    case tripConfigHelpCombinedLatMinGTitle
    case tripConfigHelpCombinedLatMinGBody
    case tripConfigHelpCombinedLatMinGMore
    case tripConfigHelpCombinedLatMinGLess
    case tripConfigHelpAccelInTurnSharpGTitle
    case tripConfigHelpAccelInTurnSharpGBody
    case tripConfigHelpAccelInTurnSharpGMore
    case tripConfigHelpAccelInTurnSharpGLess
    case tripConfigHelpAccelInTurnEmergencyGTitle
    case tripConfigHelpAccelInTurnEmergencyGBody
    case tripConfigHelpAccelInTurnEmergencyGMore
    case tripConfigHelpAccelInTurnEmergencyGLess
    case tripConfigHelpBrakeInTurnSharpGTitle
    case tripConfigHelpBrakeInTurnSharpGBody
    case tripConfigHelpBrakeInTurnSharpGMore
    case tripConfigHelpBrakeInTurnSharpGLess
    case tripConfigHelpBrakeInTurnEmergencyGTitle
    case tripConfigHelpBrakeInTurnEmergencyGBody
    case tripConfigHelpBrakeInTurnEmergencyGMore
    case tripConfigHelpBrakeInTurnEmergencyGLess
    case tripConfigHelpRoadWindowSTitle
    case tripConfigHelpRoadWindowSBody
    case tripConfigHelpRoadWindowSMore
    case tripConfigHelpRoadWindowSLess
    case tripConfigHelpRoadLowP2pGTitle
    case tripConfigHelpRoadLowP2pGBody
    case tripConfigHelpRoadLowP2pGMore
    case tripConfigHelpRoadLowP2pGLess
    case tripConfigHelpRoadHighP2pGTitle
    case tripConfigHelpRoadHighP2pGBody
    case tripConfigHelpRoadHighP2pGMore
    case tripConfigHelpRoadHighP2pGLess
    case tripConfigHelpRoadLowAbsGTitle
    case tripConfigHelpRoadLowAbsGBody
    case tripConfigHelpRoadLowAbsGMore
    case tripConfigHelpRoadLowAbsGLess
    case tripConfigHelpRoadHighAbsGTitle
    case tripConfigHelpRoadHighAbsGBody
    case tripConfigHelpRoadHighAbsGMore
    case tripConfigHelpRoadHighAbsGLess
    case tripConfigHelpDoubleCountWindowSTitle
    case tripConfigHelpDoubleCountWindowSBody
    case tripConfigHelpDoubleCountWindowSMore
    case tripConfigHelpDoubleCountWindowSLess
    case tripConfigHelpSpeedBreakpointsMsTitle
    case tripConfigHelpSpeedBreakpointsMsBody
    case tripConfigHelpSpeedBreakpointsMsMore
    case tripConfigHelpSpeedBreakpointsMsLess
    case tripConfigHelpSpeedFactorsTitle
    case tripConfigHelpSpeedFactorsBody
    case tripConfigHelpSpeedFactorsMore
    case tripConfigHelpSpeedFactorsLess
    case tripConfigHelpPenaltyAccelSharpTitle
    case tripConfigHelpPenaltyAccelSharpBody
    case tripConfigHelpPenaltyAccelSharpMore
    case tripConfigHelpPenaltyAccelSharpLess
    case tripConfigHelpPenaltyAccelEmergencyTitle
    case tripConfigHelpPenaltyAccelEmergencyBody
    case tripConfigHelpPenaltyAccelEmergencyMore
    case tripConfigHelpPenaltyAccelEmergencyLess
    case tripConfigHelpPenaltyBrakeSharpTitle
    case tripConfigHelpPenaltyBrakeSharpBody
    case tripConfigHelpPenaltyBrakeSharpMore
    case tripConfigHelpPenaltyBrakeSharpLess
    case tripConfigHelpPenaltyBrakeEmergencyTitle
    case tripConfigHelpPenaltyBrakeEmergencyBody
    case tripConfigHelpPenaltyBrakeEmergencyMore
    case tripConfigHelpPenaltyBrakeEmergencyLess
    case tripConfigHelpPenaltyTurnSharpTitle
    case tripConfigHelpPenaltyTurnSharpBody
    case tripConfigHelpPenaltyTurnSharpMore
    case tripConfigHelpPenaltyTurnSharpLess
    case tripConfigHelpPenaltyTurnEmergencyTitle
    case tripConfigHelpPenaltyTurnEmergencyBody
    case tripConfigHelpPenaltyTurnEmergencyMore
    case tripConfigHelpPenaltyTurnEmergencyLess
    case tripConfigHelpPenaltyAccelInTurnSharpTitle
    case tripConfigHelpPenaltyAccelInTurnSharpBody
    case tripConfigHelpPenaltyAccelInTurnSharpMore
    case tripConfigHelpPenaltyAccelInTurnSharpLess
    case tripConfigHelpPenaltyAccelInTurnEmergencyTitle
    case tripConfigHelpPenaltyAccelInTurnEmergencyBody
    case tripConfigHelpPenaltyAccelInTurnEmergencyMore
    case tripConfigHelpPenaltyAccelInTurnEmergencyLess
    case tripConfigHelpPenaltyBrakeInTurnSharpTitle
    case tripConfigHelpPenaltyBrakeInTurnSharpBody
    case tripConfigHelpPenaltyBrakeInTurnSharpMore
    case tripConfigHelpPenaltyBrakeInTurnSharpLess
    case tripConfigHelpPenaltyBrakeInTurnEmergencyTitle
    case tripConfigHelpPenaltyBrakeInTurnEmergencyBody
    case tripConfigHelpPenaltyBrakeInTurnEmergencyMore
    case tripConfigHelpPenaltyBrakeInTurnEmergencyLess
    case tripConfigHelpPenaltyRoadLowTitle
    case tripConfigHelpPenaltyRoadLowBody
    case tripConfigHelpPenaltyRoadLowMore
    case tripConfigHelpPenaltyRoadLowLess
    case tripConfigHelpPenaltyRoadHighTitle
    case tripConfigHelpPenaltyRoadHighBody
    case tripConfigHelpPenaltyRoadHighMore
    case tripConfigHelpPenaltyRoadHighLess
}
