//
//  LocalizationCatalog.swift
//  TelemetryApp
//
//  Created by Alex on 15.03.26.
//

import Foundation

enum LocalizationCatalog {

    static let catalog: [AppLanguage: [LocalizationKey: String]] = [
        .english: english,
        .russian: russian,
        .spanish: spanish,
        .french: french,
        .chineseSimplified: chineseSimplified,
        .hindi: hindi
    ]

    // Baseline language
    static let english: [LocalizationKey: String] = [
        .done: "Done",
        .close: "Close",
        .cancel: "Cancel",
        .loading: "Loading…",
        .settings: "Settings",
        .language: "Language",
        .openSettings: "Open Settings",

        .driverScore: "Driver Score",
        .driverScoreOneTrip: "This Trip Score",
        .recording: "Recording",
        .ready: "Ready",
        .start: "Start",
        .stop: "Stop",
        .tripHistory: "Trip History",
        .dashcam: "Dashcam",

        .driverLabel: "Driver",
        .enterDriverId: "Change Username",
        .enterDriverIdButton: "Change Username",
        .driverIdRequired: "A username is created automatically",

        .tripArchiveTitle: "Trip History (longer than 0,3 km)",
        .tripDate: "Date",
        .score: "Score",
        .km: "km",
        .kmh: "km/h",
        .noTripsInArchive: "No trips longer than 0,3 km in archive",
        .archiveLoadError: "Failed to load archive",

        .tripDuration: "Trip Duration",
        .averageSpeed: "Average Speed",
        .notEnoughData: "Not enough data",
        .excellent: "Excellent",
        .verySmooth: "Very smooth",
        
        .driverIdSection: "Username",
        .current: "Current",
        .changeDriverId: "Change Username",

        .privacy: "Privacy",
        .privacyDescription: "In this edition, technical identifiers are hidden from the public UI. You can remove locally stored app data from this device.",
        .deleteLocalData: "Delete Local Data",
        .delete: "Delete",
        .deleteLocalDataTitle: "Delete local data?",
        .deleteLocalDataMessage: "This will remove app data stored locally on this device.",

        .backgroundLocation: "Background Location",
        .backgroundLocationFooter: "For stable GPS tracking in background, iOS requires Always permission. With When In Use, background updates may be limited by the system.",
        .gpsDeniedTitle: "GPS access denied",
        .gpsDeniedMessage: "GPS access is disabled in iOS Settings (Never or restricted). Allow location access, otherwise telemetry and trips may not be recorded.",
        .openIOSSettings: "Open iOS Settings",
        .alwaysRequiredTitle: "To run the app in background, you need to change the permission to Always",
        .alwaysRequiredMessage: "Current permission is When In Use. In background, iOS may limit updates, and trip tracking/scoring may become inaccurate.",
        .requestAlways: "Open iOS Settings and Request Always",
        .locationPermissionRequiredTitle: "Location permission required",
        .locationPermissionRequiredMessage: "Allow location access to record telemetry. Always permission will be needed for stable background operation.",
        .allowLocation: "Allow Location",
        .tripRecordingInProgress: "Trip recording in progress",
        .readyToStartTrip: "Ready to start trip",
        
        .change: "Change",
        .passwordConfirmationRequired: "Password confirmation is required for this username on this device",
        .gps: "GPS",
        .unstableOperationTitle: "Operation may be unstable",
        .alwaysPermissionHint: "For reliable trip recording in background, enable Always location permission in iOS Settings.",
        .tripTime: "Trip Time",
        .distance: "Distance",
        .server: "Server",
        .deviceShort: "Device",
        .saveFishGame: "Save the Fish Game",
        .monitoring: "Monitoring",
        .activity: "Activity",
        .state: "State",
        .tripsToday: "Trips Today",
        .dayMonitoringNote: "iOS activity detection does not distinguish a private car from public transport at this layer. Right now only automotive is detected; finer classification will be added later.",
        .viewTripHistory: "Open Trip History",
        .offlineFinishMessage: "Trip finished successfully.\nTrip reports will appear after connection to the server is restored.",
        .searchingServerMessage: "Finishing trip. Looking for Telemetry server…",
        .autoFinishSearchingMessage: "Trip was auto-finished. Finishing and retrieving report…",
        .autoFinished: "Trip auto-finished",
        .tripFinishingGettingReport: "Trip finished. Retrieving report…",
        .driverAuthUnavailable: "Driver ID verification failed: EU/RU servers temporarily unavailable",
        .enableMonitoring: "Enable monitoring",
        .disableMonitoring: "Disable monitoring",
        .driver: "Driver",
        .driverIdSetupDescription: "A username is created automatically on first launch. You can change it here if you want to use your own profile.",

        .continueButton: "Continue",
        .password: "Password",
        .create: "Create",
        .signIn: "Sign In",
        .back: "Back",
        .checking: "Checking…",
        .newDriverPasswordPrompt: "This username does not exist yet. Set a password to create it.",

        .existingDriverPasswordPrompt: "This username already exists. Enter its password to use it on this device.",

        .serverStillRequiresPassword: "The server still requires a password for this username on this device.",
        .driverIdNotCreatedOnServer: "The username was not created on the server.",
       
        
        .driverLoginMissing: "Driver login is not set",

        .report: "Report",
        .reportLoading: "Loading report…",
        .reportLoadError: "Failed to load report",
        
        .preliminaryReport: "Preliminary report",
        .batchData: "Batch data",
        .sent: "Sent",
        .notSent: "Not sent",
        .total: "Total",
        .serverProcessing: "Still processing on server",
        .autoFinishLabel: "Finish: Auto",
        .drivingMode: "Driving Mode",
        .drivingLoad: "Driving Load",
        .yourAverageRating: "Your average rating",
        .countedTripsYouHave: "Counted trips you have",
        .comparisonUnavailable: "Comparison is not available yet",
        .eventSummary: "Event Summary",
        .dangerousManeuvers: "Dangerous maneuvers",
        .skidRisk: "Skid risk",
        .roadAnomalies: "Road anomalies",
        .detailsV2: "What affected the score",
        .details: "Details",
        .poor: "Poor",
        .normal: "Normal",
        .good: "Good",
        .needsMoreCare: "Needs more care",
        .someSharpMoments: "Some sharp moments",
        .almostPerfect: "Almost perfect",
        .outOf: "out of",
        .driversGenitive: "drivers",
        .betterThanPrevTripsPrefix: "Better than",
        .betterThanPrevTripsSuffix: "of your previous trips",
        .betterThanAllTripsPrefix: "Better than",
        .betterThanAllTripsSuffix: "of all drivers' trips",
        .totalTripsCounted: "Total trips counted",
        .tripReportTitle: "Trip Report",
        
        .yourTrip: "Your Trip",
        .totals: "Totals",
        .stops: "Stops",
        .comparison: "Comparison",
        .startLabel: "Start",
        .finishLabel: "Finish",
        .meters: "m",
        .vsPreviousTrip: "Vs your previous trips",
        .vsAllTrips: "Vs all drivers trips",
        .previousTripsDriver: "Previous trips (driver)",
        .allTripsInDatabase: "All trips in database",
        .driverRank: "Driver rank",
        .totalDrivers: "Total drivers",
        .driverAverageScore: "Driver average score",
        .driverTripsCount: "Driver trips count",
        
        .drivingModeMixed: "Mixed",
        .drivingModeCity: "City",
        .drivingModeHighway: "Highway",
        .drivingModeUnknown: "Unknown",
      
        
        .stopsCount: "Number of stops",
        .stopsTotal: "Total stop time",
        .stopsP95: "Stop duration (P95)",
        .stopsPerKm: "Stops per km",
        .seconds: "sec",
        
        .eventClassesV2: "Event Classes",
        .eventClassSharpHelp: "• sharp — sharp maneuver. There is risk, but it is usually controlled.",
        .eventClassEmergencyHelp: "• emergency — emergency maneuver. More severe than the threshold, higher risk.",
        .eventClassAccelBrakeTurnHelp: "• accel/brake/turn — based on acceleration projections (a_long_g / a_lat_g).",
        .eventClassAccelBrakeInTurnHelp: "• accel_in_turn/brake_in_turn — combination of longitudinal and lateral acceleration (skid risk).",
        .eventClassRoadAnomalyHelp: "• road_anomaly — vertical spikes (a_vert_g) + severity estimation.",
        .eventClassesImportantNote: "Important: final “danger” depends on speed — scoring takes speed_m_s into account.",
        
        .glassGameRunning: "How smooth is your driving?",
        .glassGameOver: "Game over.\nYou spilled the whole glass",
        .glassGameSpilled: "Total spilled:",
        .glassGameBonus: "Refill bonus:",
        .glassGameHint: "Move the glass carefully — water reacts to motion and spills. The fish may die!",
        .glassGameSpilledShort: "Spilled:",
        .dashcamTeaserMessage:
        "Version 2.0 will surprise you here.\nDon't miss the new app release.",
        .currentSpeed: "Current speed",
        
        .accelerationSharp: "Acceleration (sharp)",
        .accelerationEmergency: "Acceleration (emergency)",
        .brakingSharp: "Braking (sharp)",
        .brakingEmergency: "Braking (emergency)",
        .turnsSharp: "Turns (sharp)",
        .turnsEmergency: "Turns (emergency)",
        .accelerationInTurn: "Acceleration in turn",
        .brakingInTurn: "Braking in turn",
        .roadAnomaliesLow: "Road anomalies (low)",
        .roadAnomaliesHigh: "Road anomalies (high)",
        
        .yourDrivingLevelToday: "Your level today:",
        .betterThanDriversPercent: "better than %d%% of drivers",
        .topDriversPercent: "Top %d%% of drivers",
        
        .currentDrivingLevel: "Current driving level:",
        .scoreDeltaLastTrips: "%@ over the last 5 trips",
        .ratingFormingTripsLeft: "Rating is being formed — %d more trips needed",
        .toNextLevelLeft: "%@ left to reach %@",
        .missingDeviceId: "Missing device ID",

        .driverLevelRisky: "Risky Driver",
        .driverLevelAverage: "Calm Driver",
        .driverLevelSafe: "Confident Driver",
        .driverLevelPro: "Professional Driver",
        
        .lastFiveTripsTitle: "Last 5 trips",
        .excellentSeriesFiveOfFive: "Excellent streak: 5 of 5",
        .goodSeriesFourOfFive: "Good streak: 4 of 5",
        .decentSeriesThreeOfFive: "Not bad streak: 3 of 5",
        .tripCanBeImproved: "There is a trip that can be improved",
        .keepGreenSeriesNextTrip: "Keep the green streak in your next trip",
        .restoreGreenSeriesNextTrip: "Try to bring back the green streak in your next trip",
        .retry: "Retry",
        
        .privacyPolicy: "Privacy Policy",
        .termsOfUse: "Terms of Use",

        .account: "Account",
        .deleteAccount: "Delete Account",
        .deleteAccountTitle: "Delete account?",
        .deleteAccountMessage: "This permanently deletes your account and associated app data that we are not required to retain.",
        .unableToDeleteAccount: "Unable to delete account",
        .accountNotFound: "Account not found",
        .errorGeneric: "Something went wrong",
        .ok: "OK",

        .changeDriverDuringTripTitle: "Change driver during active trip?",
        .changeDriverDuringTripMessage: "The current trip will be stopped and finished with the current driver ID. After that, you can sign in with a new driver ID.",

        .onboardingTitle: "Drive safer and smarter",
        .onboardingAutoDetect: "Automatically detect trips",
        .onboardingSummary: "Show trip summary and driving score",
        .onboardingEvents: "Detect braking, acceleration, and turns",
        .onboardingBackground: "Keep trip recording reliable in background",
        .onboardingPermissionText: "We request Location and Motion access only to record trips, detect driving events, and calculate your driving score.",

        .crashDetected: "Crash detected",
        .crashImpactFormat: "%.2f g impact",
        
        .driverId: "Username",
        .deviceConfirmationFailed: "Unable to confirm this device. Please use a real device.",
        .loginFailedTryAgain: "Unable to sign in. Please try again.",
        
        .driverIdNotFound: "Username not found",
        .invalidPassword: "Incorrect password",
        
        .deviceNotAuthorizedForDriver: "This device is not authorized for this username",
        .archiveNotFound: "Trip history not found",
        .archiveLoadFailedGeneric: "Unable to load trip history",
        
        
        
        
    ]

    static let russian: [LocalizationKey: String] = [
        .done: "Готово",
        .close: "Закрыть",
        .cancel: "Отмена",
        .loading: "Загрузка…",
        .settings: "Настройки",
        .language: "Язык",
        .openSettings: "Открыть настройки",

        .driverScore: "Оценка вождения",
        .driverScoreOneTrip: "Рейтинг этой поездки",
        .recording: "Запись",
        .ready: "Готово",
        .start: "Старт",
        .stop: "Стоп",
        .tripHistory: "Архив поездок",
        .dashcam: "Видеорежим",

        .driverLabel: "Водитель",


        .tripArchiveTitle: "Архив поездок длиной более 0,3 км.",
        .tripDate: "Дата",
        .score: "Оценка",
        .km: "км",
        .kmh: "км/ч",
        .noTripsInArchive: "Нет поездок в архиве длиной более 0,3 км.",
        .archiveLoadError: "Ошибка загрузки архива",

        .tripDuration: "Длительность поездки",
        .averageSpeed: "Средняя скорость",
        .notEnoughData: "Недостаточно данных",
        .excellent: "Отлично",
        .verySmooth: "Очень аккуратно",
                
        .current: "Текущий",
       
        .privacy: "Конфиденциальность",
        .privacyDescription: "В данной версии приложения технические идентификаторы скрыты из публичного интерфейса. Вы можете удалить локально сохранённые данные приложения на этом устройстве.",
        .deleteLocalData: "Удалить локальные данные",
        .delete: "Удалить",
        .deleteLocalDataTitle: "Удалить локальные данные?",
        .deleteLocalDataMessage: "Это удалит локально сохранённые данные приложения на этом устройстве.",

        .backgroundLocation: "Локация (фон)",
        .backgroundLocationFooter: "Для стабильной работы GPS в фоне iOS требует разрешение Всегда. При включеном режиме Только при использовании фон может быть ограничен системой.",
        .gpsDeniedTitle: "GPS не разрешён",
        .gpsDeniedMessage: "GPS запрещён в настройках iOS (режим «Никогда» или ограничения). Разрешите доступ к геопозиции, иначе телеметрия и поездки могут не записываться.",
        .openIOSSettings: "Открыть настройки iOS",
        .alwaysRequiredTitle: "Для работы приложения в фоне требуется изменить разрешние на Всегда",
        .alwaysRequiredMessage: "Сейчас разрешение: При использовании. В фоне iOS может ограничивать обновления, и поездка/скоринг будут неточными.",
        .requestAlways: "Открыть настройки iOS и Запросить Всегда",
        .locationPermissionRequiredTitle: "Требуется разрешение на геолокацию",
        .locationPermissionRequiredMessage: "Разрешите доступ к геолокации, чтобы записывать телеметрию. Для работы в фоне потребуется выбрать опцию Всегда.",
        .allowLocation: "Разрешить геолокацию",
        .tripRecordingInProgress: "Идёт запись поездки",
        .readyToStartTrip: "Готово к началу поездки",
        
        .change: "Изменить",
     
        .gps: "GPS",
        .unstableOperationTitle: "Возможна некорректная работа",
        .alwaysPermissionHint: "Для стабильной записи поездки в фоне включите разрешение Всегда (Настройки → Геолокация).",
        .tripTime: "Время поездки",
        .distance: "Дистанция",
        .server: "Сервер",
        .deviceShort: "Устр.",
        .saveFishGame: "Игра Спаси Рыбку",
        .monitoring: "Мониторинг",
        .activity: "Активность",
        .state: "Состояние",
        .tripsToday: "Поездок сегодня",
        .dayMonitoringNote: "Примечание: iOS не различает личный авто и общественный транспорт на уровне activity. Сейчас детектируем только automotive; классификацию добавим следующим этапом.",
        .viewTripHistory: "Смотреть архив поездок",
        .offlineFinishMessage: "Поездка завершена успешно.\nОтчёты поездки появятся после восстановления связи с сервером.",
        .searchingServerMessage: "Завершение поездки. Ищем сервер Telemetry…",
        .autoFinishSearchingMessage: "Поездка авто-завершена. Завершаем и получаем отчёт…",
        .autoFinished: "Поездка авто-завершена",
        .tripFinishingGettingReport: "Поездка завершена. Получаем отчёт…",
        .driverAuthUnavailable: "Не удалось проверить ID водителя: EU/RU временно недоступны",
        .enableMonitoring: "Включить мониторинг",
        .disableMonitoring: "Выключить мониторинг",
        .driver: "Водитель",

        .continueButton: "Продолжить",
        .password: "Пароль",
        .create: "Создать",
        .signIn: "Войти",
        .back: "Назад",
        .checking: "Проверяем…",
        
        .driverLoginMissing: "Не задан логин водителя",
        
        .report: "Отчёт",
        .reportLoading: "Загрузка отчёта…",
        .reportLoadError: "Ошибка загрузки отчёта",
        
        .preliminaryReport: "Отчёт предварительный",
        .batchData: "Данные по батчам",
        .sent: "Отправлено",
        .notSent: "Не отправлено",
        .total: "Всего",
        .serverProcessing: "Сервер ещё обрабатывает",
        .autoFinishLabel: "Завершение: Авто",
        .drivingMode: "Режим поездки",
        .drivingLoad: "Интенсивность вождения",
        .yourAverageRating: "Ваш средний рейтинг",
        .countedTripsYouHave: "Учитываемых поездок у вас",
        .comparisonUnavailable: "Сравнение пока недоступно",
        .eventSummary: "Сводка событий",
        .dangerousManeuvers: "Опасные манёвры",
        .skidRisk: "Риск заноса",
        .roadAnomalies: "Неровности",
        .detailsV2: "Что повлияло на оценку",
        .details: "Подробно",
        .poor: "Плохо",
        .normal: "Нормально",
        .good: "Хорошо",
        .needsMoreCare: "Нужно аккуратнее",
        .someSharpMoments: "Есть резкие моменты",
        .almostPerfect: "Почти идеально",
        .outOf: "из",
        .driversGenitive: "водителей",
        .betterThanPrevTripsPrefix: "Лучше, чем",
        .betterThanPrevTripsSuffix: "ваших предыдущих поездок",
        .betterThanAllTripsPrefix: "Лучше, чем",
        .betterThanAllTripsSuffix: "поездок всех водителей",
        .totalTripsCounted: "Всего учтено поездок",
        .tripReportTitle: "Отчёт о поездке",
        
        .yourTrip: "Ваша поездка",
        .totals: "Итоги",
        .stops: "Остановки",
        .comparison: "Сравнение",
        .startLabel: "Старт",
        .finishLabel: "Финиш",
        .meters: "м",
        .vsPreviousTrip: "Лучше ваших предыдущих поездок",
        .vsAllTrips: "Лучше всех поездок всех водителей",
        .previousTripsDriver: "Поездок ранее (этот водитель)",
        .allTripsInDatabase: "Всего поездок (в базе)",
        .driverRank: "Рейтинг этого водителя",
        .totalDrivers: "Всего водителей",
        .driverAverageScore: "Средний оценка этого водителя",
        .driverTripsCount: "Поездок у водителя",
        
        .drivingModeMixed: "Смешанный",
        .drivingModeCity: "Город",
        .drivingModeHighway: "Трасса",
        .drivingModeUnknown: "Не определён",
  
        
        .stopsCount: "Количество остановок",
        .stopsTotal: "Общее время остановок",
        .stopsP95: "Длительность остановки (P95)",
        .stopsPerKm: "Остановок на км",
        .seconds: "сек",
        
        .eventClassesV2: "Классы событий",
        .eventClassSharpHelp: "• sharp — резкое действие. Есть риск, но обычно контролируемо.",
        .eventClassEmergencyHelp: "• emergency — экстренное действие. Резче порога, выше риск.",
        .eventClassAccelBrakeTurnHelp: "• accel/brake/turn — опасные маневры -по проекциям ускорения (a_long_g / a_lat_g).",
        .eventClassAccelBrakeInTurnHelp: "• accel_in_turn/brake_in_turn — риск заноса - комбинация продольного и поперечного ускорения (риск заноса).",
        .eventClassRoadAnomalyHelp: "• неровности — вертикальные пики (a_vert_g) + оценка severity.",
        .eventClassesImportantNote: "Важно: итоговая «опасность» зависит от скорости — скоринг учитывает speed_m_s.",
        .glassGameRunning: "Как плавно вы водите?",
        .glassGameOver: "Игра остановлена.\nВы пролили весь стакан",
        .glassGameSpilled: "Всего разлили:",
        .glassGameBonus: "Получили бонусом:",
        .glassGameHint: "Осторожно передвигайте стакан — вода реагирует на движения и разливается! Рыбка может погибнуть",
        .glassGameSpilledShort: "Пролито:",
        .dashcamTeaserMessage:
        "В версии 2.0 мы вас удивим здесь.\nНе пропустите новый релиз приложения.",
        .currentSpeed: "Текущая скорость",
        
        .accelerationSharp: "Ускорения (резкие)",
        .accelerationEmergency: "Ускорения (экстренные)",
        .brakingSharp: "Торможения (резкие)",
        .brakingEmergency: "Торможения (экстренные)",
        .turnsSharp: "Повороты (резкие)",
        .turnsEmergency: "Повороты (экстренные)",
        .accelerationInTurn: "Ускорение в повороте",
        .brakingInTurn: "Торможение в повороте",
        .roadAnomaliesLow: "Неровности (низкие)",
        .roadAnomaliesHigh: "Неровности (сильные)",
        
        .yourDrivingLevelToday: "Ваш уровень сегодня:",
        .betterThanDriversPercent: "лучше, чем у %d%% водителей",
        .topDriversPercent: "Топ %d%% водителей",
        
        .currentDrivingLevel: "Текущий уровень вождения:",
        .scoreDeltaLastTrips: "%@ за последние 5 поездок",
        .ratingFormingTripsLeft: "Рейтинг формируется — нужно ещё %d поездок",
        .toNextLevelLeft: "До уровня %@ осталось %@",
        .missingDeviceId: "Отсутствует ID устройства",

        .driverLevelRisky: "Рискованный водитель",
        .driverLevelAverage: "Спокойный водитель",
        .driverLevelSafe: "Уверенный водитель",
        .driverLevelPro: "Профессиональный водитель",
        
        .lastFiveTripsTitle: "Последние 5 поездок",
        .excellentSeriesFiveOfFive: "Отличная серия: 5 из 5",
        .goodSeriesFourOfFive: "Хорошая серия: 4 из 5",
        .decentSeriesThreeOfFive: "Неплохая серия: 3 из 5",
        .tripCanBeImproved: "Есть поездка, которую можно улучшить",
        .keepGreenSeriesNextTrip: "Сохраните зелёную серию в следующей поездке",
        .restoreGreenSeriesNextTrip: "Попробуйте вернуть зелёную серию уже в следующей поездке",
        .retry: "Повторить",
        
        .privacyPolicy: "Политика конфиденциальности",
        .termsOfUse: "Условия использования",

        .account: "Аккаунт",
        .deleteAccount: "Удалить аккаунт",
        .deleteAccountTitle: "Удалить аккаунт?",
        .deleteAccountMessage: "Это навсегда удалит ваш аккаунт и связанные данные приложения, которые мы не обязаны хранить.",
        .unableToDeleteAccount: "Не удалось удалить аккаунт",
        .accountNotFound: "Аккаунт не найден",
        .errorGeneric: "Произошла ошибка",
        .ok: "ОК",

        .changeDriverDuringTripTitle: "Изменить водителя во время активной поездки?",
        .changeDriverDuringTripMessage: "Текущая поездка будет остановлена и завершена с текущим ID водителя. После этого вы сможете войти с новым ID водителя.",

        .onboardingTitle: "Водите безопаснее и умнее",
        .onboardingAutoDetect: "Автоматически определяйте поездки",
        .onboardingSummary: "Смотрите сводку поездки и оценку вождения",
        .onboardingEvents: "Определяйте торможения, ускорения и повороты",
        .onboardingBackground: "Сохраняйте надёжную запись поездки в фоне",
        .onboardingPermissionText: "Мы запрашиваем доступ к геолокации и движению только для записи поездок, определения событий вождения и расчёта вашей оценки вождения.",

        .crashDetected: "Обнаружен удар",
        .crashImpactFormat: "Удар %.2f g",
       
        .deviceConfirmationFailed: "Не удалось подтвердить устройство. Используйте реальное устройство.",
        .loginFailedTryAgain: "Не удалось выполнить вход. Попробуйте снова.",
        
        .invalidPassword: "Неверный пароль",
        
        .archiveNotFound: "Архив поездок не найден",
        .archiveLoadFailedGeneric: "Не удалось загрузить архив поездок",
      
        
        .enterDriverId: "Изменить имя пользователя",
        .enterDriverIdButton: "Изменить имя пользователя",
        .driverIdRequired: "Имя пользователя создаётся автоматически",
        .driverIdSection: "Имя пользователя",
        .changeDriverId: "Изменить имя пользователя",
        .passwordConfirmationRequired: "Для этого имени пользователя на данном устройстве требуется пароль",
        .driverIdSetupDescription: "При первом запуске имя пользователя создаётся автоматически. Здесь его можно изменить, если вы хотите использовать свой профиль.",
        .driverId: "Имя пользователя",
        .newDriverPasswordPrompt: "Такого имени пользователя ещё нет. Задайте пароль, чтобы создать его.",
        .existingDriverPasswordPrompt: "Это имя пользователя уже существует. Введите пароль, чтобы использовать его на этом устройстве.",
        .serverStillRequiresPassword: "Сервер всё ещё требует пароль для этого имени пользователя на данном устройстве.",
        .driverIdNotCreatedOnServer: "Имя пользователя не было создано на сервере.",
        .driverIdNotFound: "Имя пользователя не найдено",
        .deviceNotAuthorizedForDriver: "Это устройство не авторизовано для данного имени пользователя",             
        
    ]

    // Пока пустые
    static let spanish: [LocalizationKey: String] = [:]
    static let french: [LocalizationKey: String] = [:]
    static let chineseSimplified: [LocalizationKey: String] = [:]
    static let hindi: [LocalizationKey: String] = [:]
}
